/**
 * Go text/template codegen from Mapping Model + raw Blockly JSON.
 *
 * Preferred path is the Blockly canvas walker (`src/blockly/go_template_codegen.ts`)
 * registered as the `go-template` export adapter — Conversion start, RM JSON,
 * JSON Schema, XML, and `for_each_source`. This module is the slot / JSON-state
 * fallback (TakeCare XML snapshots, empty canvas).
 *
 * Emits Go text/template syntax with a curated Sprig-subset FuncMap:
 * replace, regexReplaceAll, trim, quote, lower, substr, int, ge.
 *
 * Execute context shape: { Parameters: defaults, Data: sourceInstance }.
 * Source queries become {{ index .Data "vitals" "systolic" }} (JSON) or a
 * single index key for FLAT/`|` and `/…` paths. Defaults Map lookups become
 * {{ .Parameters.Key }}.
 */
import type { ExprAst } from "../expression/mod.ts";
import type { MappingModel } from "../../types/mod.ts";
import { parseExpression } from "../expression/mod.ts";

export function generateGoTemplate(
  model: MappingModel,
  options?: { blocklyState?: unknown },
): string {
  const lines: string[] = [
    `{{- /* Generated by intEHRgrator — Go text/template Conversion Script */ -}}`,
    `{{- /* Target: ${model.templateId || "free-form"} */ -}}`,
  ];

  if (options?.blocklyState) {
    lines.push(generateFromBlockly(options.blocklyState, model));
  } else {
    lines.push(generateFromSlots(model));
  }

  return lines.join("\n");
}

function generateFromSlots(model: MappingModel): string {
  const lines: string[] = [];
  for (const slot of model.slots) {
    const ast = parseExpression(slot.expression);
    const goExpr = emitGoExpr(ast);
    lines.push(`{{- /* ${slot.label ?? slot.slotId} */ -}}`);
    lines.push(`{{ ${goExpr} }}`);
  }
  return lines.join("\n");
}

function generateFromBlockly(blocklyState: unknown, model: MappingModel): string {
  const state = blocklyState as { blocks?: { blocks?: unknown[] } };
  const blocks = state?.blocks?.blocks;
  if (!Array.isArray(blocks) || blocks.length === 0) {
    return generateFromSlots(model);
  }
  return emitBlockTree(blocks).join("\n");
}

interface BlockInput {
  block?: BlockNode;
  shadow?: BlockNode;
}

interface BlockNode {
  type: string;
  id?: string;
  fields?: Record<string, unknown>;
  inputs?: Record<string, BlockInput>;
  next?: { block?: BlockNode };
  extraState?: {
    attributes?: Array<{ name: string; value: string }>;
    childGroups?: string[];
    elseIfCount?: number;
    hasElse?: boolean;
    xmlAttributes?: string[];
    fields?: Array<{ name: string; xmlKind?: string }>;
  };
}

/** Blockly serializes unused default values as shadows; maps_get KEY is typically a shadow. */
function inputChild(input: BlockInput | undefined): BlockNode | undefined {
  return input?.block ?? input?.shadow;
}

function emitBlockTree(blocks: unknown[]): string[] {
  const lines: string[] = [];
  for (const block of blocks) {
    lines.push(...emitStatementChain(block as BlockNode));
  }
  return lines;
}

function emitBlock(block: BlockNode): string[] {
  const lines: string[] = [];
  if (!block) return lines;

  switch (block.type) {
    case "xml_element":
    case "target_structure": {
      lines.push(...emitXmlOrSchemaElement(block));
      break;
    }
    case "xml_text": {
      const value = block.inputs?.VALUE?.block;
      if (value) {
        lines.push(...emitValueExpression(value));
      } else {
        const text = String(block.fields?.TEXT ?? "");
        lines.push(text);
      }
      break;
    }
    case "xml_attribute": {
      break;
    }
    case "defaults_block":
    case "maps_create_with":
    case "conversion_start": {
      break;
    }
    case "for_each_source": {
      lines.push(...emitForEachSource(block));
      break;
    }
    case "json_object":
    case "json_array": {
      lines.push(...emitJsonStructure(block));
      break;
    }
    case "controls_if": {
      lines.push(...emitControlsIf(block));
      break;
    }
    case "text":
    case "text_code": {
      lines.push(String(block.fields?.TEXT ?? ""));
      break;
    }
    case "text_handlebars": {
      const script = block.inputs?.SCRIPT?.block;
      if (script) {
        lines.push(...emitValueExpression(script));
      }
      break;
    }
    case "source_query":
    case "source_query_number":
    case "source_query_boolean":
    case "source_query_node": {
      const expr = String(block.fields?.EXPRESSION ?? "");
      lines.push(`{{ ${goIndexExpr(expr)} }}`);
      break;
    }
    case "maps_get": {
      const name = String(block.fields?.NAME ?? "defaults");
      const key = inputChild(block.inputs?.KEY);
      const keyStr = key ? extractTextValue(key) : "";
      if (name === "defaults" || name === "Parameters") {
        lines.push(`{{ .Parameters.${sanitizeGoField(keyStr)} }}`);
      } else {
        lines.push(`{{ index .${sanitizeGoField(name)} ${goQuote(keyStr)} }}`);
      }
      break;
    }
    default:
      if (block.type.startsWith("schema_")) {
        lines.push(...emitXmlOrSchemaElement(block));
      } else {
        lines.push(`{{- /* unsupported block: ${block.type} */ -}}`);
      }
  }

  return lines;
}

function emitStatementChain(block: BlockNode): string[] {
  const lines: string[] = [];
  let current: BlockNode | undefined = block;
  while (current) {
    lines.push(...emitBlock(current));
    current = current.next?.block;
  }
  return lines;
}

function emitValueExpression(block: BlockNode): string[] {
  switch (block.type) {
    case "source_query":
    case "source_query_number":
    case "source_query_boolean":
    case "source_query_node": {
      const expr = String(block.fields?.EXPRESSION ?? "");
      return [`{{ ${goIndexExpr(expr)} }}`];
    }
    case "maps_get": {
      const name = String(block.fields?.NAME ?? "defaults");
      const key = inputChild(block.inputs?.KEY);
      const keyStr = key ? extractTextValue(key) : "";
      if (name === "defaults" || name === "Parameters") {
        return [`{{ .Parameters.${sanitizeGoField(keyStr)} }}`];
      }
      return [`{{ index .${sanitizeGoField(name)} ${goQuote(keyStr)} }}`];
    }
    case "text":
      return [String(block.fields?.TEXT ?? "")];
    case "text_code":
      return [String(block.fields?.TEXT ?? "")];
    case "math_number":
      return [String(block.fields?.NUM ?? "0")];
    case "logic_boolean":
      return [block.fields?.BOOL === "TRUE" ? "true" : "false"];
    case "text_changeCase": {
      const inner = block.inputs?.TEXT?.block;
      const caseType = String(block.fields?.CASE ?? "LOWERCASE");
      if (inner) {
        const innerExpr = emitValueExpression(inner).join("");
        if (caseType === "LOWERCASE") return [`{{ ${stripDelimiters(innerExpr)} | lower }}`];
        if (caseType === "UPPERCASE") return [`{{ ${stripDelimiters(innerExpr)} | upper }}`];
      }
      return emitValueExpression(inner!);
    }
    case "text_trim": {
      const inner = block.inputs?.TEXT?.block;
      if (inner) {
        const innerExpr = emitValueExpression(inner).join("");
        return [`{{ ${stripDelimiters(innerExpr)} | trim }}`];
      }
      return [];
    }
    default:
      return [`{{- /* value: ${block.type} */ -}}`];
  }
}

function emitControlsIf(block: BlockNode): string[] {
  const lines: string[] = [];
  const elseCount = (block as BlockNode & { extraState?: { elseIfCount?: number; hasElse?: boolean } })
    .extraState;
  const ifCount = (elseCount?.elseIfCount ?? 0) + 1;

  for (let i = 0; i < ifCount; i++) {
    const cond = block.inputs?.[`IF${i}`]?.block;
    const body = block.inputs?.[`DO${i}`]?.block;
    const keyword = i === 0 ? "if" : "else if";
    const condStr = cond ? emitConditionExpression(cond) : "true";
    lines.push(`{{- ${keyword} ${condStr} }}`);
    if (body) lines.push(...emitStatementChain(body));
  }

  if (elseCount?.hasElse) {
    const elseBody = block.inputs?.ELSE?.block;
    lines.push(`{{- else }}`);
    if (elseBody) lines.push(...emitStatementChain(elseBody));
  }

  lines.push(`{{- end }}`);
  return lines;
}

function emitConditionExpression(block: BlockNode): string {
  switch (block.type) {
    case "logic_compare": {
      const op = String(block.fields?.OP ?? "EQ");
      const a = block.inputs?.A?.block;
      const b = block.inputs?.B?.block;
      const aStr = a ? emitInlineValue(a) : '""';
      const bStr = b ? emitInlineValue(b) : '""';
      const goOp = { EQ: "eq", NEQ: "ne", LT: "lt", LTE: "le", GT: "gt", GTE: "ge" }[op] ?? "eq";
      return `${goOp} ${aStr} ${bStr}`;
    }
    case "logic_operation": {
      const op = String(block.fields?.OP ?? "AND").toLowerCase();
      const a = block.inputs?.A?.block;
      const b = block.inputs?.B?.block;
      const aStr = a ? `(${emitConditionExpression(a)})` : "true";
      const bStr = b ? `(${emitConditionExpression(b)})` : "true";
      return `${op} ${aStr} ${bStr}`;
    }
    case "logic_negate": {
      const inner = block.inputs?.BOOL?.block;
      return inner ? `not (${emitConditionExpression(inner)})` : "true";
    }
    default:
      return emitInlineValue(block);
  }
}

function emitInlineValue(block: BlockNode): string {
  switch (block.type) {
    case "source_query":
    case "source_query_number":
    case "source_query_boolean":
    case "source_query_node": {
      const expr = String(block.fields?.EXPRESSION ?? "");
      return `(${goIndexExpr(expr)})`;
    }
    case "maps_get": {
      const name = String(block.fields?.NAME ?? "defaults");
      const key = inputChild(block.inputs?.KEY);
      const keyStr = key ? extractTextValue(key) : "";
      if (name === "defaults" || name === "Parameters") {
        return `.Parameters.${sanitizeGoField(keyStr)}`;
      }
      return `(index .${sanitizeGoField(name)} ${goQuote(keyStr)})`;
    }
    case "text":
      return goQuote(String(block.fields?.TEXT ?? ""));
    case "text_code":
      return goQuote(String(block.fields?.TEXT ?? ""));
    case "math_number":
      return String(block.fields?.NUM ?? "0");
    case "logic_boolean":
      return block.fields?.BOOL === "TRUE" ? "true" : "false";
    default:
      return `""`;
  }
}

function emitXmlOrSchemaElement(block: BlockNode): string[] {
  if (block.type === "xml_element") return emitXmlElement(block);
  const tag = xmlTagName(block);
  const xmlAttributes = new Set([
    ...(block.extraState?.xmlAttributes ?? []),
    ...(block.extraState?.fields ?? [])
      .filter((field) => field.xmlKind === "attribute")
      .map((field) => field.name),
  ]);
  const attrParts: string[] = [...emitStaticAttributes(block)];
  const inner: string[] = [];
  const inputs = block.inputs ?? {};
  for (const [key, value] of Object.entries(inputs)) {
    if (!key.startsWith("TARGET_") && !key.startsWith("SCHEMA_OPT_")) continue;
    const fieldName = key.replace(/^TARGET_|^SCHEMA_OPT_/, "");
    const child = inputChild(value);
    if (!child) continue;
    if (xmlAttributes.has(fieldName) || child.type === "xml_attribute") {
      const val = emitValueExpression(child).join("");
      attrParts.push(` ${fieldName}="${val}"`);
      continue;
    }
    if (isXmlStructureBlockType(child.type)) {
      inner.push(...emitStatementChain(child));
      continue;
    }
    inner.push(`<${xmlName(fieldName)}>`, ...emitValueExpression(child), `</${xmlName(fieldName)}>`);
  }
  const attrs = attrParts.join("");
  if (inner.length) return [`<${tag}${attrs}>`, ...inner, `</${tag}>`];
  return [`<${tag}${attrs}></${tag}>`];
}

function isXmlStructureBlockType(type: string): boolean {
  return type === "xml_element" || type === "target_structure" || type.startsWith("schema_") ||
    type === "controls_if" || type === "for_each_source" || type === "for_each_list" ||
    type === "json_object" || type === "json_array";
}

function emitForEachSource(block: BlockNode): string[] {
  const name = String(block.fields?.VAR ?? "item").trim() || "item";
  const ident = /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : "item";
  const path = String(block.fields?.PATH ?? "/");
  const coll = goIndexExpr(path);
  const body = block.inputs?.DO?.block;
  const lines = [`{{- range $i, $${ident} := (${coll}) }}`];
  if (body) lines.push(...emitStatementChain(body));
  lines.push(`{{- end }}`);
  return lines;
}

function emitJsonStructure(block: BlockNode): string[] {
  const isArray = block.type === "json_array";
  const props: string[] = [];
  const inputs = block.inputs ?? {};
  for (const [key, value] of Object.entries(inputs)) {
    if (!key.startsWith("TARGET_") && !key.startsWith("SCHEMA_OPT_")) continue;
    const fieldName = key.replace(/^TARGET_|^SCHEMA_OPT_/, "");
    const child = inputChild(value);
    if (!child) continue;
    const rendered = emitValueExpression(child).join("");
    if (isArray) props.push(rendered);
    else props.push(`${JSON.stringify(fieldName)}: ${jsonishValue(child, rendered)}`);
  }
  if (isArray) return [`[${props.join(", ")}]`];
  if (!props.length) return ["{}"];
  return ["{", props.map((p) => `  ${p}`).join(",\n"), "}"];
}

function jsonishValue(block: BlockNode, rendered: string): string {
  if (block.type === "math_number" || block.type === "source_query_number" ||
    block.type === "logic_boolean" || block.type === "json_null" ||
    block.type === "json_object" || block.type === "json_array" ||
    block.type.startsWith("schema_")) {
    return rendered.startsWith("{{") || rendered.startsWith("{") || rendered.startsWith("[") ||
        rendered === "true" || rendered === "false" || rendered === "null" ||
        /^-?\d/.test(rendered)
      ? rendered
      : `{{ ${stripDelimiters(rendered)} }}`;
  }
  if (rendered.startsWith("{{") && rendered.includes("| quote")) return rendered;
  if (rendered.startsWith("{{")) {
    return `{{ ${stripDelimiters(rendered)} | quote }}`;
  }
  return JSON.stringify(rendered);
}

function xmlName(value: string): string {
  const safe = value.replace(/[^A-Za-z0-9_.-]/g, "_");
  return /^[A-Za-z_]/.test(safe) ? safe : `_${safe}`;
}

function emitXmlElement(block: BlockNode): string[] {
  const tag = xmlTagName(block);
  const bodyHead = firstChildStatement(block);
  const attrParts: string[] = [...emitStaticAttributes(block)];
  const body: BlockNode[] = [];
  let current: BlockNode | undefined = bodyHead;
  while (current) {
    if (current.type === "xml_attribute") {
      const name = String(current.fields?.NAME ?? "").trim();
      if (name) {
        const valBlock = inputChild(current.inputs?.VALUE);
        const val = valBlock ? emitValueExpression(valBlock).join("") : "";
        attrParts.push(` ${name}="${val}"`);
      }
    } else {
      body.push(current);
    }
    current = current.next?.block;
  }
  const attrs = attrParts.join("");
  if (body.length) {
    const inner: string[] = [];
    for (const child of body) inner.push(...emitBlock(child));
    return [`<${tag}${attrs}>`, ...inner, `</${tag}>`];
  }
  return [`<${tag}${attrs} />`];
}

function xmlTagName(block: BlockNode): string {
  const slot = String(block.fields?.SLOT_ID ?? "");
  const path = slot.includes(":") ? slot.slice(slot.indexOf(":") + 1) : slot;
  const fromPath = path.split("/").filter((part) => part && !part.startsWith("@")).pop();
  if (fromPath) return fromPath;
  const name = String(block.fields?.NAME ?? "element").trim();
  return name || "element";
}

function firstChildStatement(block: BlockNode): BlockNode | undefined {
  const inputs = block.inputs ?? {};
  if (inputs.TARGET_children?.block) return inputs.TARGET_children.block;
  for (const [key, value] of Object.entries(inputs)) {
    if (key.startsWith("TARGET_") && value?.block) return value.block;
  }
  return undefined;
}

function emitStaticAttributes(block: BlockNode): string[] {
  const attrs: string[] = [];
  for (const attr of block.extraState?.attributes ?? []) {
    const name = String(attr.name ?? "").trim();
    if (!name) continue;
    attrs.push(` ${name}="${String(attr.value ?? "")}"`);
  }
  let i = 0;
  while (block.fields?.[`ATTR_NAME${i}`] !== undefined) {
    const name = String(block.fields[`ATTR_NAME${i}`]);
    const valBlock = inputChild(block.inputs?.[`ATTR_VALUE${i}`]);
    const val = valBlock
      ? emitValueExpression(valBlock).join("")
      : String(block.fields?.[`ATTR_VALUE${i}`] ?? "");
    attrs.push(` ${name}="${val}"`);
    i++;
  }
  return attrs;
}

function extractTextValue(block: BlockNode): string {
  if (block.type === "text") return String(block.fields?.TEXT ?? "");
  if (block.type === "text_code") return String(block.fields?.TEXT ?? "");
  return String(block.fields?.TEXT ?? block.fields?.EXPRESSION ?? "");
}

function stripDelimiters(expr: string): string {
  return expr.replace(/^\{\{\s*/, "").replace(/\s*\}\}$/, "");
}

export function goQuote(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function sanitizeGoField(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

export interface GoExprOptions {
  /** Root pipeline for relative / JSON paths (`.Data` or `$item`). */
  loopRoot?: string;
}

/** `$.a.b[0].c` → `index .Data "a" "b" 0 "c"`; FLAT/`|` keys stay one index. */
export function goIndexExpr(path: string, root = ".Data"): string {
  const trimmed = path.trim();
  if (!trimmed || trimmed === "$" || trimmed === "$.") return root;
  if (trimmed.startsWith("/") || trimmed.includes("|")) {
    return `index ${root} ${goQuote(trimmed)}`;
  }
  let body = trimmed;
  if (body.startsWith("$.")) body = body.slice(2);
  else if (body.startsWith("$")) body = body.slice(1);
  const segments = parseJsonPathSegments(body);
  if (!segments.length) return root;
  const args = segments.map((seg) => typeof seg === "number" ? String(seg) : goQuote(seg));
  return `index ${root} ${args.join(" ")}`;
}

function parseJsonPathSegments(body: string): Array<string | number> {
  const segments: Array<string | number> = [];
  let i = 0;
  while (i < body.length) {
    if (body[i] === ".") {
      i++;
      continue;
    }
    if (body[i] === "[") {
      const close = body.indexOf("]", i + 1);
      if (close < 0) break;
      const token = body.slice(i + 1, close);
      if (/^\d+$/.test(token)) segments.push(Number(token));
      else if (
        (token.startsWith('"') && token.endsWith('"')) ||
        (token.startsWith("'") && token.endsWith("'"))
      ) {
        segments.push(token.slice(1, -1));
      } else {
        segments.push(token);
      }
      i = close + 1;
      continue;
    }
    let end = i;
    while (end < body.length && !".[".includes(body[end]!)) end++;
    if (end > i) segments.push(body.slice(i, end));
    i = end;
  }
  return segments;
}

function xpathRoot(path: string, options?: GoExprOptions): string {
  const trimmed = path.trim();
  const relative = Boolean(trimmed) && !trimmed.startsWith("$") && !trimmed.startsWith("/");
  if (relative && options?.loopRoot) return options.loopRoot;
  return ".Data";
}

export function emitGoExpr(ast: ExprAst, options?: GoExprOptions): string {
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return goQuote(ast.value);
      if (typeof ast.value === "boolean") return ast.value ? "true" : "false";
      return String(ast.value);
    case "call": {
      switch (ast.name) {
        case "xpathString":
        case "xpathNumber":
        case "xpathBoolean":
        case "xpathNode":
        case "xpath": {
          const path = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "";
          return goIndexExpr(path, xpathRoot(path, options));
        }
        case "maps_get": {
          const mapName = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "defaults";
          const key = ast.args[1]?.kind === "literal" ? String(ast.args[1].value) : "";
          if (mapName === "defaults") return `.Parameters.${sanitizeGoField(key)}`;
          return `index .${sanitizeGoField(mapName)} ${goQuote(key)}`;
        }
        case "trim":
          return `${emitGoExpr(ast.args[0]!, options)} | trim`;
        case "concat":
          return ast.args.map((a) => `{{ ${emitGoExpr(a, options)} }}`).join("");
        case "if": {
          const cond = emitGoExpr(ast.args[0]!, options);
          const then = emitGoExpr(ast.args[1]!, options);
          const els = ast.args[2] ? emitGoExpr(ast.args[2], options) : '""';
          return `if ${cond} }}{{ ${then} }}{{ else }}{{ ${els} }}{{ end`;
        }
        case "eq":
          return `eq ${emitGoExpr(ast.args[0]!, options)} ${emitGoExpr(ast.args[1]!, options)}`;
        case "ne":
          return `ne ${emitGoExpr(ast.args[0]!, options)} ${emitGoExpr(ast.args[1]!, options)}`;
        case "and":
          return `and (${emitGoExpr(ast.args[0]!, options)}) (${emitGoExpr(ast.args[1]!, options)})`;
        case "or":
          return `or (${emitGoExpr(ast.args[0]!, options)}) (${emitGoExpr(ast.args[1]!, options)})`;
        case "not":
          return `not (${emitGoExpr(ast.args[0]!, options)})`;
        case "var": {
          const name = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "item";
          return `$${sanitizeGoField(name)}`;
        }
        default:
          return `/* unsupported: ${ast.name} */`;
      }
      break;
    }
    case "binary":
      return `/* binary ${ast.op} not supported in Go template */`;
  }
}
