/**
 * Go text/template codegen from Mapping Model + Blockly workspace.
 *
 * Emits Go text/template syntax with a curated Sprig-subset FuncMap:
 * replace, regexReplaceAll, trim, quote, lower, substr, int, ge.
 *
 * Execute context shape: { Parameters: defaults, Data: sourceInstance }.
 * Source queries become {{ index .Data "flat/path|value" }}.
 * Defaults Map lookups become {{ .Parameters.Key }}.
 */
import type { ExprAst } from "../expression/mod.ts";
import type { MappingModel } from "../../types/mod.ts";
import { parseExpression } from "../expression/mod.ts";

export function generateGoTemplate(
  model: MappingModel,
  options?: { blocklyState?: unknown },
): string {
  const lines: string[] = [
    `{{- /* Generated by intEHRgrator — Go text/template Conversion Script */ -}}`,
    `{{- /* Target: ${model.templateId || "free-form"} */ -}}`,
  ];

  if (options?.blocklyState) {
    lines.push(generateFromBlockly(options.blocklyState, model));
  } else {
    lines.push(generateFromSlots(model));
  }

  return lines.join("\n");
}

function generateFromSlots(model: MappingModel): string {
  const lines: string[] = [];
  for (const slot of model.slots) {
    const ast = parseExpression(slot.expression);
    const goExpr = emitGoExpr(ast);
    lines.push(`{{- /* ${slot.label ?? slot.slotId} */ -}}`);
    lines.push(`{{ ${goExpr} }}`);
  }
  return lines.join("\n");
}

function generateFromBlockly(blocklyState: unknown, model: MappingModel): string {
  const state = blocklyState as { blocks?: { blocks?: unknown[] } };
  const blocks = state?.blocks?.blocks;
  if (!Array.isArray(blocks) || blocks.length === 0) {
    return generateFromSlots(model);
  }
  return emitBlockTree(blocks).join("\n");
}

interface BlockNode {
  type: string;
  id?: string;
  fields?: Record<string, unknown>;
  inputs?: Record<string, { block?: BlockNode }>;
  next?: { block?: BlockNode };
  extraState?: {
    attributes?: Array<{ name: string; value: string }>;
    childGroups?: string[];
    elseIfCount?: number;
    hasElse?: boolean;
  };
}

function emitBlockTree(blocks: unknown[]): string[] {
  const lines: string[] = [];
  for (const block of blocks) {
    lines.push(...emitStatementChain(block as BlockNode));
  }
  return lines;
}

function emitBlock(block: BlockNode): string[] {
  const lines: string[] = [];
  if (!block) return lines;

  switch (block.type) {
    case "xml_element": {
      lines.push(...emitXmlElement(block));
      break;
    }
    case "xml_text": {
      const value = block.inputs?.VALUE?.block;
      if (value) {
        lines.push(...emitValueExpression(value));
      } else {
        const text = String(block.fields?.TEXT ?? "");
        lines.push(text);
      }
      break;
    }
    case "xml_attribute": {
      break;
    }
    case "controls_if": {
      lines.push(...emitControlsIf(block));
      break;
    }
    case "text":
    case "text_code": {
      lines.push(String(block.fields?.TEXT ?? ""));
      break;
    }
    case "text_handlebars": {
      const script = block.inputs?.SCRIPT?.block;
      if (script) {
        lines.push(...emitValueExpression(script));
      }
      break;
    }
    case "source_query":
    case "source_query_number":
    case "source_query_boolean":
    case "source_query_node": {
      const expr = String(block.fields?.EXPRESSION ?? "");
      lines.push(`{{ index .Data ${goQuote(expr)} }}`);
      break;
    }
    case "maps_get": {
      const name = String(block.fields?.NAME ?? "defaults");
      const key = block.inputs?.KEY?.block;
      const keyStr = key ? extractTextValue(key) : "";
      if (name === "defaults" || name === "Parameters") {
        lines.push(`{{ .Parameters.${sanitizeGoField(keyStr)} }}`);
      } else {
        lines.push(`{{ index .${sanitizeGoField(name)} ${goQuote(keyStr)} }}`);
      }
      break;
    }
    default:
      lines.push(`{{- /* unsupported block: ${block.type} */ -}}`);
  }

  return lines;
}

function emitStatementChain(block: BlockNode): string[] {
  const lines: string[] = [];
  let current: BlockNode | undefined = block;
  while (current) {
    lines.push(...emitBlock(current));
    current = current.next?.block;
  }
  return lines;
}

function emitValueExpression(block: BlockNode): string[] {
  switch (block.type) {
    case "source_query":
    case "source_query_number":
    case "source_query_boolean":
    case "source_query_node": {
      const expr = String(block.fields?.EXPRESSION ?? "");
      return [`{{ index .Data ${goQuote(expr)} }}`];
    }
    case "maps_get": {
      const name = String(block.fields?.NAME ?? "defaults");
      const key = block.inputs?.KEY?.block;
      const keyStr = key ? extractTextValue(key) : "";
      if (name === "defaults" || name === "Parameters") {
        return [`{{ .Parameters.${sanitizeGoField(keyStr)} }}`];
      }
      return [`{{ index .${sanitizeGoField(name)} ${goQuote(keyStr)} }}`];
    }
    case "text":
      return [String(block.fields?.TEXT ?? "")];
    case "text_code":
      return [String(block.fields?.TEXT ?? "")];
    case "math_number":
      return [String(block.fields?.NUM ?? "0")];
    case "logic_boolean":
      return [block.fields?.BOOL === "TRUE" ? "true" : "false"];
    case "text_changeCase": {
      const inner = block.inputs?.TEXT?.block;
      const caseType = String(block.fields?.CASE ?? "LOWERCASE");
      if (inner) {
        const innerExpr = emitValueExpression(inner).join("");
        if (caseType === "LOWERCASE") return [`{{ ${stripDelimiters(innerExpr)} | lower }}`];
        if (caseType === "UPPERCASE") return [`{{ ${stripDelimiters(innerExpr)} | upper }}`];
      }
      return emitValueExpression(inner!);
    }
    case "text_trim": {
      const inner = block.inputs?.TEXT?.block;
      if (inner) {
        const innerExpr = emitValueExpression(inner).join("");
        return [`{{ ${stripDelimiters(innerExpr)} | trim }}`];
      }
      return [];
    }
    default:
      return [`{{- /* value: ${block.type} */ -}}`];
  }
}

function emitControlsIf(block: BlockNode): string[] {
  const lines: string[] = [];
  const elseCount = (block as BlockNode & { extraState?: { elseIfCount?: number; hasElse?: boolean } })
    .extraState;
  const ifCount = (elseCount?.elseIfCount ?? 0) + 1;

  for (let i = 0; i < ifCount; i++) {
    const cond = block.inputs?.[`IF${i}`]?.block;
    const body = block.inputs?.[`DO${i}`]?.block;
    const keyword = i === 0 ? "if" : "else if";
    const condStr = cond ? emitConditionExpression(cond) : "true";
    lines.push(`{{- ${keyword} ${condStr} }}`);
    if (body) lines.push(...emitStatementChain(body));
  }

  if (elseCount?.hasElse) {
    const elseBody = block.inputs?.ELSE?.block;
    lines.push(`{{- else }}`);
    if (elseBody) lines.push(...emitStatementChain(elseBody));
  }

  lines.push(`{{- end }}`);
  return lines;
}

function emitConditionExpression(block: BlockNode): string {
  switch (block.type) {
    case "logic_compare": {
      const op = String(block.fields?.OP ?? "EQ");
      const a = block.inputs?.A?.block;
      const b = block.inputs?.B?.block;
      const aStr = a ? emitInlineValue(a) : '""';
      const bStr = b ? emitInlineValue(b) : '""';
      const goOp = { EQ: "eq", NEQ: "ne", LT: "lt", LTE: "le", GT: "gt", GTE: "ge" }[op] ?? "eq";
      return `${goOp} ${aStr} ${bStr}`;
    }
    case "logic_operation": {
      const op = String(block.fields?.OP ?? "AND").toLowerCase();
      const a = block.inputs?.A?.block;
      const b = block.inputs?.B?.block;
      const aStr = a ? `(${emitConditionExpression(a)})` : "true";
      const bStr = b ? `(${emitConditionExpression(b)})` : "true";
      return `${op} ${aStr} ${bStr}`;
    }
    case "logic_negate": {
      const inner = block.inputs?.BOOL?.block;
      return inner ? `not (${emitConditionExpression(inner)})` : "true";
    }
    default:
      return emitInlineValue(block);
  }
}

function emitInlineValue(block: BlockNode): string {
  switch (block.type) {
    case "source_query":
    case "source_query_number":
    case "source_query_boolean":
    case "source_query_node": {
      const expr = String(block.fields?.EXPRESSION ?? "");
      return `(index .Data ${goQuote(expr)})`;
    }
    case "maps_get": {
      const name = String(block.fields?.NAME ?? "defaults");
      const key = block.inputs?.KEY?.block;
      const keyStr = key ? extractTextValue(key) : "";
      if (name === "defaults" || name === "Parameters") {
        return `.Parameters.${sanitizeGoField(keyStr)}`;
      }
      return `(index .${sanitizeGoField(name)} ${goQuote(keyStr)})`;
    }
    case "text":
      return goQuote(String(block.fields?.TEXT ?? ""));
    case "text_code":
      return goQuote(String(block.fields?.TEXT ?? ""));
    case "math_number":
      return String(block.fields?.NUM ?? "0");
    case "logic_boolean":
      return block.fields?.BOOL === "TRUE" ? "true" : "false";
    default:
      return `""`;
  }
}

function emitXmlElement(block: BlockNode): string[] {
  const tag = xmlTagName(block);
  const bodyHead = firstChildStatement(block);
  const attrParts: string[] = [...emitStaticAttributes(block)];
  const body: BlockNode[] = [];
  let current: BlockNode | undefined = bodyHead;
  while (current) {
    if (current.type === "xml_attribute") {
      const name = String(current.fields?.NAME ?? "").trim();
      if (name) {
        const valBlock = current.inputs?.VALUE?.block;
        const val = valBlock ? emitValueExpression(valBlock).join("") : "";
        attrParts.push(` ${name}="${val}"`);
      }
    } else {
      body.push(current);
    }
    current = current.next?.block;
  }
  const legacyText = block.inputs?.TEXT?.block;
  const attrs = attrParts.join("");
  if (body.length || legacyText) {
    const inner: string[] = [];
    if (legacyText) inner.push(...emitBlock(legacyText));
    for (const child of body) inner.push(...emitBlock(child));
    return [`<${tag}${attrs}>`, ...inner, `</${tag}>`];
  }
  return [`<${tag}${attrs} />`];
}

function xmlTagName(block: BlockNode): string {
  const name = String(block.fields?.NAME ?? block.fields?.TAG ?? "element").trim();
  return name || "element";
}

function firstChildStatement(block: BlockNode): BlockNode | undefined {
  const inputs = block.inputs ?? {};
  if (inputs.TARGET_children?.block) return inputs.TARGET_children.block;
  if (inputs.CHILDREN?.block) return inputs.CHILDREN.block;
  for (const [key, value] of Object.entries(inputs)) {
    if (key.startsWith("TARGET_") && value?.block) return value.block;
  }
  return undefined;
}

function emitStaticAttributes(block: BlockNode): string[] {
  const attrs: string[] = [];
  for (const attr of block.extraState?.attributes ?? []) {
    const name = String(attr.name ?? "").trim();
    if (!name) continue;
    attrs.push(` ${name}="${String(attr.value ?? "")}"`);
  }
  let i = 0;
  while (block.fields?.[`ATTR_NAME${i}`] !== undefined) {
    const name = String(block.fields[`ATTR_NAME${i}`]);
    const valBlock = block.inputs?.[`ATTR_VALUE${i}`]?.block;
    const val = valBlock
      ? emitValueExpression(valBlock).join("")
      : String(block.fields?.[`ATTR_VALUE${i}`] ?? "");
    attrs.push(` ${name}="${val}"`);
    i++;
  }
  return attrs;
}

function extractTextValue(block: BlockNode): string {
  if (block.type === "text") return String(block.fields?.TEXT ?? "");
  if (block.type === "text_code") return String(block.fields?.TEXT ?? "");
  return String(block.fields?.TEXT ?? block.fields?.EXPRESSION ?? "");
}

function stripDelimiters(expr: string): string {
  return expr.replace(/^\{\{\s*/, "").replace(/\s*\}\}$/, "");
}

function goQuote(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function sanitizeGoField(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function emitGoExpr(ast: ExprAst): string {
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return `index .Data ${goQuote(ast.value)}`;
      return String(ast.value);
    case "call": {
      switch (ast.name) {
        case "xpathString": /* falls through */
        case "xpathNumber": /* falls through */
        case "xpathBoolean": /* falls through */
        case "xpathNode": /* falls through */
        case "xpath": {
          const path = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "";
          return `index .Data ${goQuote(path)}`;
        }
        case "maps_get": {
          const mapName = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "defaults";
          const key = ast.args[1]?.kind === "literal" ? String(ast.args[1].value) : "";
          if (mapName === "defaults") return `.Parameters.${sanitizeGoField(key)}`;
          return `index .${sanitizeGoField(mapName)} ${goQuote(key)}`;
        }
        case "trim": return `${emitGoExpr(ast.args[0]!)} | trim`;
        case "concat": return ast.args.map((a) => `{{ ${emitGoExpr(a)} }}`).join("");
        case "if": {
          const cond = emitGoExpr(ast.args[0]!);
          const then = emitGoExpr(ast.args[1]!);
          const els = ast.args[2] ? emitGoExpr(ast.args[2]) : '""';
          return `if ${cond} }}{{ ${then} }}{{ else }}{{ ${els} }}{{ end`;
        }
        default:
          return `/* unsupported: ${ast.name} */`;
      }
      break;
    }
    case "binary":
      return `/* binary ${ast.op} not supported in Go template */`;
  }
}
