import type { ExportTarget, MappingModel } from "../../types/mod.ts";
import { parseExpression, serialize } from "../expression/mod.ts";

export function generateTypeScript(model: MappingModel): string {
  const lines: string[] = [
    "// Generated by intEHRgrator — Conversion Script (TypeScript / ehrtslib)",
    `// Template: ${model.templateId}`,
    "",
    "import * as openehr_rm from 'ehrtslib/openehr_rm.ts';",
    "import {",
    "  evaluateXPathToString,",
    "  evaluateXPathToNumber,",
    "  evaluateXPathToBoolean,",
    "} from 'fontoxpath';",
    "",
    "export type SourceContext = { format: 'json' | 'xml'; data: unknown };",
    "",
    "function evalExpr(expr: string, sourceCtx: SourceContext): unknown {",
    "  // Expression dispatch generated per slot at export time",
    "  return __evalGenerated(expr, sourceCtx);",
    "}",
    "",
    "export async function convertSourceToComposition(sourceCtx: SourceContext) {",
    "  const composition = new openehr_rm.COMPOSITION();",
    "",
  ];

  for (const slot of model.slots) {
    lines.push(`  // ${slot.slotId}`);
    lines.push(`  // expression: ${slot.expression}`);
    lines.push(
      `  // TODO: wire to RM path — magnitude/units from ${slot.rmType}`,
    );
    lines.push(
      `  void evalExpr(${JSON.stringify(slot.expression)}, sourceCtx);`,
    );
    lines.push("");
  }

  lines.push("  return composition;", "}", "");
  lines.push(buildEvalHelper(model));
  return lines.join("\n");
}

function buildEvalHelper(model: MappingModel): string {
  const cases = model.slots.map((slot) => {
    const ast = parseExpression(slot.expression);
    const body = emitTsEval(ast, "sourceCtx");
    return `  if (expr === ${JSON.stringify(slot.expression)}) {\n    return ${body};\n  }`;
  });
  return [
    "function __evalGenerated(expr: string, sourceCtx: SourceContext): unknown {",
    ...cases,
    "  throw new Error('Unknown expression: ' + expr);",
    "}",
  ].join("\n");
}

function emitTsEval(ast: import("@intehrgrator/core/expression/mod.ts").ExprAst, ctx: string): string {
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return JSON.stringify(ast.value);
      return String(ast.value);
    case "binary":
      return `(${emitTsEval(ast.left, ctx)} ${ast.op} ${emitTsEval(ast.right, ctx)})`;
    case "call": {
      const args = ast.args.map((a) => emitTsEval(a, ctx));
      const node = `${ctx}.data`;
      switch (ast.name) {
        case "trim":
          return `String(${args[0]}).trim()`;
        case "concat":
          return `[${args.join(", ")}].join('')`;
        case "if":
          return `(${args[0]} ? ${args[1]} : ${args[2]})`;
        case "switch":
          return emitSwitchTs(args);
        case "var":
          return `__vars[${args[0]}]`;
        case "xpathString":
          return `evaluateXPathToString(${args[0]}, ${node})`;
        case "xpathNumber":
          return `evaluateXPathToNumber(${args[0]}, ${node})`;
        case "xpathBoolean":
          return `evaluateXPathToBoolean(${args[0]}, ${node})`;
        default:
          return `evaluateXPathToString(${args[0]}, ${node})`;
      }
    }
  }
}

function emitSwitchTs(args: string[]): string {
  if (args.length < 2) return "null";
  const discriminant = args[0];
  const defaultV = args[args.length - 1];
  const pairs = args.slice(1, -1);
  let expr = defaultV;
  for (let i = pairs.length - 2; i >= 0; i -= 2) {
    expr = `(${discriminant} === ${pairs[i]} ? ${pairs[i + 1]} : ${expr})`;
  }
  return expr;
}

export function generateJava(model: MappingModel): string {
  const lines: string[] = [
    "// Generated by intEHRgrator — Conversion Script (Java / Archie)",
    `// Template: ${model.templateId}`,
    "package com.regionstockholm.intehrgrator.generated;",
    "",
    "import com.nedap.archie.rm.composition.Composition;",
    "",
    "public class ConversionScript {",
    "  public Composition convert(Object source) {",
    "    Composition composition = new Composition();",
  ];

  for (const slot of model.slots) {
    lines.push(`    // ${slot.slotId} = ${serialize(parseExpression(slot.expression))}`);
  }

  lines.push("    return composition;", "  }", "}");
  return lines.join("\n");
}

export function generate(model: MappingModel, target: ExportTarget): string {
  return target === "java" ? generateJava(model) : generateTypeScript(model);
}
