import type { ExportTarget, MappingModel } from "../../types/mod.ts";
import { parseExpression, serialize } from "../expression/mod.ts";
import { precompileHandlebars } from "../output/handlebars_dialect.ts";
import { generateXQuery } from "./xquery.ts";

export {
  compileLiteralPath,
  emitXQueryExpr,
  generateXQuery,
  jsonDollarPathToLookup,
} from "./xquery.ts";

export interface ExportGenerationOptions {
  handlebarsTemplate?: string;
  precompile?: boolean;
}

export interface ExportTargetAdapter {
  readonly id: ExportTarget;
  readonly extension: string;
  readonly mime: string;
  generate(model: MappingModel, options?: ExportGenerationOptions): string;
}

export function generateTypeScript(model: MappingModel): string {
  const lines: string[] = [
    "// Generated by intEHRgrator — Conversion Script (TypeScript / ehrtslib)",
    `// Template: ${model.templateId}`,
    "",
    "import * as openehr_rm from 'ehrtslib/openehr_rm.ts';",
    "import {",
    "  evaluateXPathToString,",
    "  evaluateXPathToNumber,",
    "  evaluateXPathToBoolean,",
    "} from 'fontoxpath';",
    "",
    "export type SourceContext = { format: string; data: unknown };",
    "",
    "function evalExpr(expr: string, sourceCtx: SourceContext): unknown {",
    "  // Expression dispatch generated per slot at export time",
    "  return __evalGenerated(expr, sourceCtx);",
    "}",
    "",
    "export async function convertSourceToComposition(sourceCtx: SourceContext) {",
    "  const composition = new openehr_rm.COMPOSITION();",
    "",
  ];

  for (const slot of model.slots) {
    lines.push(`  // ${slot.slotId}`);
    lines.push(`  // expression: ${slot.expression}`);
    lines.push(
      `  // TODO: wire to RM path — magnitude/units from ${slot.rmType}`,
    );
    lines.push(
      `  void evalExpr(${JSON.stringify(slot.expression)}, sourceCtx);`,
    );
    lines.push("");
  }

  lines.push("  return composition;", "}", "");
  lines.push(buildEvalHelper(model));
  return lines.join("\n");
}

function buildEvalHelper(model: MappingModel): string {
  const cases = model.slots.map((slot) => {
    const ast = parseExpression(slot.expression);
    const body = emitTsEval(ast, "sourceCtx");
    return `  if (expr === ${JSON.stringify(slot.expression)}) {\n    return ${body};\n  }`;
  });
  return [
    "function __evalGenerated(expr: string, sourceCtx: SourceContext): unknown {",
    ...cases,
    "  throw new Error('Unknown expression: ' + expr);",
    "}",
  ].join("\n");
}

function emitTsEval(ast: import("@intehrgrator/core/expression/mod.ts").ExprAst, ctx: string): string {
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return JSON.stringify(ast.value);
      return String(ast.value);
    case "binary":
      return `(${emitTsEval(ast.left, ctx)} ${ast.op} ${emitTsEval(ast.right, ctx)})`;
    case "call": {
      const args = ast.args.map((a) => emitTsEval(a, ctx));
      const node = `${ctx}.data`;
      switch (ast.name) {
        case "trim":
          return `String(${args[0]}).trim()`;
        case "concat":
          return `[${args.join(", ")}].join('')`;
        case "if":
          return `(${args[0]} ? ${args[1]} : ${args[2]})`;
        case "switch":
          return emitSwitchTs(args);
        case "var":
          return `__vars[${args[0]}]`;
        case "xpathString":
          return `evaluateXPathToString(${args[0]}, ${node})`;
        case "xpathNumber":
          return `evaluateXPathToNumber(${args[0]}, ${node})`;
        case "xpathBoolean":
          return `evaluateXPathToBoolean(${args[0]}, ${node})`;
        default:
          return `evaluateXPathToString(${args[0]}, ${node})`;
      }
    }
  }
}

function emitSwitchTs(args: string[]): string {
  if (args.length < 2) return "null";
  const discriminant = args[0];
  const defaultV = args[args.length - 1];
  const pairs = args.slice(1, -1);
  let expr = defaultV;
  for (let i = pairs.length - 2; i >= 0; i -= 2) {
    expr = `(${discriminant} === ${pairs[i]} ? ${pairs[i + 1]} : ${expr})`;
  }
  return expr;
}

export function generateJava(model: MappingModel): string {
  const lines: string[] = [
    "// Generated by intEHRgrator — Conversion Script (Java / Archie)",
    `// Template: ${model.templateId}`,
    "package com.regionstockholm.intehrgrator.generated;",
    "",
    "import com.nedap.archie.rm.composition.Composition;",
    "",
    "public class ConversionScript {",
    "  public Composition convert(Object source) {",
    "    Composition composition = new Composition();",
  ];

  for (const slot of model.slots) {
    lines.push(`    // ${slot.slotId} = ${serialize(parseExpression(slot.expression))}`);
  }

  lines.push("    return composition;", "  }", "}");
  return lines.join("\n");
}

export function generateHandlebars(
  model: MappingModel,
  options: ExportGenerationOptions = {},
): string {
  const source = options.handlebarsTemplate?.trim()
    ? options.handlebarsTemplate
    : [
      "{{!-- Generated by intEHRgrator — Kintegrate-compatible Handlebars dialect --}}",
      `{{!-- Target: ${model.templateId} --}}`,
      ...model.slots.map((slot) =>
        `{{!-- ${slot.label ?? slot.slotId} --}}{{{json (slot ${JSON.stringify(slot.slotId)})}}}`
      ),
    ].join("\n");
  return options.precompile ? precompileHandlebars(source) : source;
}

const adapters = new Map<ExportTarget, ExportTargetAdapter>([
  ["typescript", {
    id: "typescript",
    extension: "ts",
    mime: "text/typescript",
    generate: generateTypeScript,
  }],
  ["java", {
    id: "java",
    extension: "java",
    mime: "text/x-java-source",
    generate: generateJava,
  }],
  ["handlebars", {
    id: "handlebars",
    extension: "hbs",
    mime: "text/x-handlebars-template",
    generate: generateHandlebars,
  }],
  ["xquery", {
    id: "xquery",
    extension: "xq",
    mime: "application/xquery",
    generate: generateXQuery,
  }],
]);

export function registerExportTargetAdapter(adapter: ExportTargetAdapter): void {
  adapters.set(adapter.id, adapter);
}

export function getExportTargetAdapter(target: ExportTarget): ExportTargetAdapter {
  const adapter = adapters.get(target);
  if (!adapter) throw new Error(`Unsupported export target: ${target}`);
  return adapter;
}

export function generate(
  model: MappingModel,
  target: ExportTarget,
  options?: ExportGenerationOptions,
): string {
  return getExportTargetAdapter(target).generate(model, options);
}
