/**
 * XQuery conversion script language — Mapping Model → self-contained `.xq`.
 *
 * Model B slot-manifest plus IR loops as `for $x in … return` and a pruned
 * `targetSignature` tree (`element node`). Full COMPOSITION RM XML (Model A/C)
 * remains a follow-up. Convert-time `$source`, `$defaults`, and `$sheets`
 * are external (ADR 0002 / 0005). In-app Test Run does not execute this `.xq`.
 *
 * See docs/future/xquery-export-investigation.md and docs/XQUERY_ENGINE.md.
 */
import type {
  MappingLoop,
  MappingModel,
  MappingSlot,
  TargetSignatureNode,
} from "../../types/mod.ts";
import { parseExpression, type ExprAst, isQuantifyCall } from "../expression/mod.ts";
import { expressionUsesRelativeSourcePath } from "../mapping_model/loops.ts";
import { isSheetAccessor } from "../sheets/evaluate.ts";

export interface XqEmitEnv {
  /** Context item for relative source paths (`$source` or a loop variable). */
  ctx: string;
  /** Loop / grain names → XQuery NCName. */
  bind: Record<string, string>;
  warnings: string[];
}

function createXqEmitEnv(ctx = "$source"): XqEmitEnv {
  return { ctx, bind: {}, warnings: [] };
}

export function generateXQuery(model: MappingModel): string {
  const env = createXqEmitEnv();
  const body = emitMappingResult(model, env);
  const removed = (model.unsupported ?? []).filter((item) => item.reason === "removed");

  const lines: string[] = [
    'xquery version "3.1";',
    "",
    "(: Generated by intEHRgrator — Conversion Script (XQuery) :)",
    `(: Target: ${xqComment(model.templateId)} :)`,
    `(: Target instance format: ${xqComment(model.targetFormat ?? "openehr-template")} :)`,
    "(: Runtime: BaseX (preferred oracle) or Saxon-HE / eXist — see docs/XQUERY_ENGINE.md :)",
    "(: Bind $source as XPath 3.1 map (JSON via parse-json / json-doc) or XML node. :)",
    "(: Bind $defaults and $sheets as maps at convert time (not baked literals). :)",
    "(: Output: mapping-result with nested target nodes + slots. Full COMPOSITION RM XML is deferred. :)",
    "(: In-app Test Run continues to use Mapping Model + Target instance format — not this .xq. :)",
    "",
  ];

  if (removed.length) {
    for (const item of removed) {
      lines.push(
        `(: VMS-removed block ${xqComment(item.blockType)} skipped — not emitted :)` +
          (item.slotId ? ` (: slot ${xqComment(item.slotId)} :)` : ""),
      );
    }
    lines.push("");
  }

  if (env.warnings.length) {
    lines.push("(: Conversion script warnings — dynamic paths use local:*-at runtime helpers :)");
    for (const warning of env.warnings) {
      lines.push(`(:  - ${xqComment(warning)} :)`);
    }
    lines.push("");
  }

  lines.push(
    'declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";',
    'declare namespace rm = "http://schemas.openehr.org/v1";',
    'declare namespace xsi = "http://www.w3.org/2001/XMLSchema-instance";',
    'declare namespace map = "http://www.w3.org/2005/xpath-functions/map";',
    "",
    'declare option output:method "xml";',
    'declare option output:indent "yes";',
    "",
    "declare variable $source external;",
    "declare variable $defaults as map(*) external := map {};",
    "declare variable $sheets as map(*) external := map {};",
    "",
    ...emitHelpers(),
    "",
    "declare function local:convert($source as item()*) as element(mapping-result) {",
    indent(body, 1),
    "};",
    "",
    "local:convert($source)",
    "",
  );
  return lines.join("\n");
}

function emitMappingResult(model: MappingModel, env: XqEmitEnv): string {
  const assignment = assignSlotsToLoops(model);
  const pruned = (model.targetSignature ?? [])
    .map((node) => pruneSignature(node, model))
    .filter((node): node is TargetSignatureNode => node !== null);
  const attachesInTree = new Set<string>();
  const collectAttaches = (node: TargetSignatureNode) => {
    if ((model.loops ?? []).some((loop) => loop.attachSlotId === node.slotId)) {
      attachesInTree.add(node.slotId);
    }
    for (const child of node.children) collectAttaches(child);
  };
  for (const root of pruned) collectAttaches(root);

  const parts: string[] = [`attribute template { ${xqString(model.templateId)} }`];
  const target = emitTargetTree(model, env, assignment, pruned);
  if (target) parts.push(target);
  const slots = emitSlotsElement(model, env, assignment, attachesInTree);
  if (slots) parts.push(slots);
  if (parts.length === 1) {
    return `element mapping-result {\n${indent(parts[0]!, 1)}\n  (: no mapped slots — map Target value slots in Blockly, then re-export :)\n}`;
  }
  return `element mapping-result {\n${indent(parts.join(",\n"), 1)}\n}`;
}

function emitTargetTree(
  model: MappingModel,
  env: XqEmitEnv,
  assignment: Map<string, MappingLoop>,
  roots: TargetSignatureNode[],
): string | null {
  if (!roots.length) return null;
  const children = roots
    .map((node) => emitSignatureNode(node, model, env, assignment))
    .filter(Boolean);
  if (!children.length) return null;
  return `element target {\n${indent(children.join(",\n"), 1)}\n}`;
}

function emitSlotsElement(
  model: MappingModel,
  env: XqEmitEnv,
  assignment: Map<string, MappingLoop>,
  attachesInTree: Set<string>,
): string | null {
  const loops = model.loops ?? [];
  const parts: string[] = [];

  for (const slot of model.slots) {
    const loop = assignment.get(slot.slotId);
    if (loop && attachesInTree.has(loop.attachSlotId)) continue;
    if (loop) continue;
    parts.push(emitSlot(slot, env).join("\n"));
  }

  for (const loop of loops) {
    if (attachesInTree.has(loop.attachSlotId)) continue;
    const members = model.slots.filter((slot) => assignment.get(slot.slotId) === loop);
    if (!members.length) {
      parts.push(emitEmptyLoop(loop, env));
      continue;
    }
    const inner = loopEnv(loop, env);
    const body = members.map((slot) => emitSlot(slot, inner).join("\n")).join(",\n");
    parts.push(`${emitForHead(loop, env)} return (\n${indent(body, 1)}\n)`);
  }

  if (!parts.length) return null;
  return `element slots {\n${indent(parts.join(",\n"), 1)}\n}`;
}

function emitEmptyLoop(loop: MappingLoop, env: XqEmitEnv): string {
  return `${emitForHead(loop, env)} return\n${indent(
    [
      "element loop {",
      `  attribute attach-slot-id { ${xqString(loop.attachSlotId)} },`,
      `  attribute var-name { ${xqString(loop.varName)} },`,
      `  attribute kind { ${xqString(loop.kind ?? "source")} }`,
      "}",
    ].join("\n"),
    1,
  )}`;
}

function emitSignatureNode(
  node: TargetSignatureNode,
  model: MappingModel,
  env: XqEmitEnv,
  assignment: Map<string, MappingLoop>,
): string {
  const loop = (model.loops ?? []).find((item) => item.attachSlotId === node.slotId);
  const inner = loop ? loopEnv(loop, env) : env;
  const slotMap = new Map(model.slots.map((slot) => [slot.slotId, slot]));
  const parts: string[] = [
    `attribute slot-id { ${xqString(node.slotId)} }`,
    `attribute rm-type { ${xqString(node.rmType)} }`,
  ];
  if (node.label) parts.push(`attribute label { ${xqString(node.label)} }`);
  if (loop) {
    parts.push(`attribute var-name { ${xqString(loop.varName)} }`);
    parts.push(`attribute kind { ${xqString(loop.kind ?? "source")} }`);
    if (loop.path) parts.push(`attribute path { ${xqString(loop.path)} }`);
    if (loop.collection) parts.push(`attribute collection { ${xqString(loop.collection)} }`);
  }
  const slot = slotMap.get(node.slotId);
  if (slot) parts.push(emitSlot(slot, inner).join("\n"));
  for (const child of node.children) {
    parts.push(emitSignatureNode(child, model, inner, assignment));
  }
  if (loop) {
    const inTree = signatureSubtreeIds(model, loop.attachSlotId);
    for (const extra of model.slots) {
      if (assignment.get(extra.slotId) === loop && !inTree.has(extra.slotId)) {
        parts.push(emitSlot(extra, inner).join("\n"));
      }
    }
  }
  const element = `element node {\n${indent(parts.join(",\n"), 1)}\n}`;
  if (!loop) return element;
  return `${emitForHead(loop, env)} return\n${indent(element, 1)}`;
}

function emitForHead(loop: MappingLoop, env: XqEmitEnv): string {
  const ident = xqIdent(loop.varName);
  return `for $${ident} in ${emitLoopSequence(loop, env)}`;
}

function emitLoopSequence(loop: MappingLoop, env: XqEmitEnv): string {
  if ((loop.kind ?? "source") === "list") {
    if (!loop.collection?.trim()) return "()";
    try {
      return `local:unbox(${emitXQueryExprInner(parseExpression(loop.collection), env)})`;
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return `(: unparseable collection: ${xqComment(msg)} :) ()`;
    }
  }
  const path = loop.path.trim();
  const compiled = compileSequencePath(path, "$source");
  if (compiled) return `local:unbox(${compiled})`;
  env.warnings.push(`loop ${loop.varName}: dynamic collection path uses local:nodes-at`);
  return `local:nodes-at($source, ${xqString(path)})`;
}

function loopEnv(loop: MappingLoop, env: XqEmitEnv): XqEmitEnv {
  const ident = xqIdent(loop.varName);
  return {
    ctx: `$${ident}`,
    bind: { ...env.bind, [loop.varName]: ident },
    warnings: env.warnings,
  };
}

function assignSlotsToLoops(model: MappingModel): Map<string, MappingLoop> {
  const assigned = new Map<string, MappingLoop>();
  const loops = model.loops ?? [];
  const ranked = [...loops].sort(
    (a, b) => signatureDepth(model, a.attachSlotId) - signatureDepth(model, b.attachSlotId),
  );
  for (const loop of ranked) {
    for (const id of signatureSubtreeIds(model, loop.attachSlotId)) {
      assigned.set(id, loop);
    }
  }
  const leftover = model.slots.filter((slot) =>
    !assigned.has(slot.slotId) && slotBelongsToSomeLoop(slot, loops)
  );
  if (leftover.length && loops.length) {
    for (const slot of leftover) {
      const named = loops.find((loop) => slotUsesLoopVar(slot, loop));
      if (named) assigned.set(slot.slotId, named);
      else if (loops.length === 1) assigned.set(slot.slotId, loops[0]!);
    }
  }
  return assigned;
}

function slotBelongsToSomeLoop(slot: MappingSlot, loops: MappingLoop[]): boolean {
  if (expressionUsesRelativeSourcePath(slot.expression)) return true;
  return loops.some((loop) => slotUsesLoopVar(slot, loop));
}

function slotUsesLoopVar(slot: MappingSlot, loop: MappingLoop): boolean {
  return slot.expression.includes(`var(${JSON.stringify(loop.varName)})`) ||
    slot.expression.includes(`var("${loop.varName}")`);
}

function signatureDepth(model: MappingModel, slotId: string): number {
  const walk = (nodes: TargetSignatureNode[], depth: number): number | null => {
    for (const node of nodes) {
      if (node.slotId === slotId) return depth;
      const found = walk(node.children, depth + 1);
      if (found !== null) return found;
    }
    return null;
  };
  return walk(model.targetSignature ?? [], 0) ?? 0;
}

function signatureSubtreeIds(model: MappingModel, slotId: string): Set<string> {
  const ids = new Set<string>();
  const node = findSignatureNode(model.targetSignature ?? [], slotId);
  if (!node) return ids;
  const collect = (current: TargetSignatureNode) => {
    ids.add(current.slotId);
    for (const child of current.children) collect(child);
  };
  collect(node);
  return ids;
}

function findSignatureNode(
  nodes: TargetSignatureNode[],
  slotId: string,
): TargetSignatureNode | undefined {
  for (const node of nodes) {
    if (node.slotId === slotId) return node;
    const child = findSignatureNode(node.children, slotId);
    if (child) return child;
  }
  return undefined;
}

function pruneSignature(node: TargetSignatureNode, model: MappingModel): TargetSignatureNode | null {
  const children = node.children
    .map((child) => pruneSignature(child, model))
    .filter((child): child is TargetSignatureNode => child !== null);
  const keep = model.slots.some((slot) => slot.slotId === node.slotId) ||
    (model.loops ?? []).some((loop) => loop.attachSlotId === node.slotId) ||
    children.length > 0;
  if (!keep) return null;
  return { ...node, children };
}

function emitHelpers(): string[] {
  return [
    "(: --- Sequences / JSON arrays --- :)",
    "",
    "declare function local:unbox($value as item()*) as item()* {",
    "  if (count($value) eq 1 and head($value) instance of array(*)) then head($value)?*",
    "  else $value",
    "};",
    "",
    "declare function local:nodes-at($ctx as item()*, $path as xs:string) as item()* {",
    "  local:unbox(local:lookup($ctx, $path))",
    "};",
    "",
    "(: --- Source access (fontoxpath-authored paths → XQuery 3.1) --- :)",
    "",
    "declare function local:string-at($ctx as item()*, $path as xs:string) as xs:string? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:string($value)",
    "};",
    "",
    "declare function local:number-at($ctx as item()*, $path as xs:string) as xs:decimal? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:decimal($value)",
    "};",
    "",
    "declare function local:boolean-at($ctx as item()*, $path as xs:string) as xs:boolean? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:boolean($value)",
    "};",
    "",
    "declare function local:lookup($ctx as item()*, $path as xs:string) as item()* {",
    "  if (starts-with($path, \"$\")) then local:json-lookup($ctx, $path)",
    "  else if (starts-with($path, \"/\")) then error(",
    '    QName("http://intehrgrator.local/xquery", "DYNAMIC-XML-PATH"),',
    '    "Prefer compile-time literal XML paths from intEHRgrator export; got: " || $path',
    "  )",
    "  else local:json-lookup($ctx, concat(\"$.\", $path))",
    "};",
    "",
    "declare function local:json-lookup($ctx as item()*, $path as xs:string) as item()* {",
    "  let $body := replace(replace($path, \"^\\\\$\\\\.?\", \"\"), \"\\\\[(\\\\d+|\\\\*)\\\\]\", \".$1\")",
    "  let $segments := tokenize($body, \"\\\\.\")[. ne \"\"]",
    "  return fold-left(",
    "    $segments,",
    "    $ctx,",
    "    function($acc as item()*, $seg as xs:string) as item()* {",
    "      if (empty($acc)) then ()",
    "      else if ($seg eq \"*\") then local:unbox($acc)",
    "      else if (count($acc) eq 1 and head($acc) instance of array(*) and $seg castable as xs:integer)",
    "        then head($acc)?(xs:integer($seg))",
    "      else if ($seg castable as xs:integer) then $acc[xs:integer($seg)]",
    "      else if (count($acc) eq 1 and head($acc) instance of map(*))",
    "        then local:unbox(map:get(head($acc), $seg))",
    "      else $acc?($seg)",
    "    }",
    "  )",
    "};",
    "",
    "(: --- Convert-time Sheets (ADR 0005) — bind $sheets as a name → grid map --- :)",
    "",
    ...emitSheetHelpers(),
    "",
    "(: --- DV_* constructors (RM XML) --- :)",
    "",
    "declare function local:dv-text($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_TEXT" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-coded-text($value as xs:string?, $code as xs:string?, $terminology as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_CODED_TEXT" },',
    "    element rm:value { $value },",
    "    element rm:defining_code {",
    "      element rm:terminology_id { element rm:value { $terminology } },",
    "      element rm:code_string { $code }",
    "    }",
    "  }",
    "};",
    "",
    "declare function local:dv-quantity($magnitude as xs:decimal?, $units as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_QUANTITY" },',
    "    element rm:magnitude { $magnitude },",
    "    element rm:units { $units }",
    "  }",
    "};",
    "",
    "declare function local:dv-count($magnitude as xs:integer?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_COUNT" },',
    "    element rm:magnitude { $magnitude }",
    "  }",
    "};",
    "",
    "declare function local:dv-boolean($value as xs:boolean?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_BOOLEAN" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-date-time($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_DATE_TIME" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-uri($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_URI" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:as-value($rm-type as xs:string, $value as item()*) as element()* {",
    "  switch ($rm-type)",
    '    case "DV_QUANTITY" return local:dv-quantity(($value)[1] ! xs:decimal(.), ())',
    '    case "DV_COUNT" return local:dv-count(($value)[1] ! xs:integer(.))',
    '    case "DV_INTEGER" return local:dv-count(($value)[1] ! xs:integer(.))',
    '    case "DV_BOOLEAN" return local:dv-boolean(($value)[1] ! xs:boolean(.))',
    '    case "DV_DATE_TIME" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_DATE" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_TIME" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_URI" return local:dv-uri(($value)[1] ! xs:string(.))',
    '    case "DV_EHR_URI" return local:dv-uri(($value)[1] ! xs:string(.))',
    '    case "DV_CODED_TEXT" return local:dv-coded-text(($value)[1] ! xs:string(.), (), ())',
    "    default return local:dv-text(($value)[1] ! xs:string(.))",
    "};",
  ];
}

function emitSheetHelpers(): string[] {
  return [
    "declare function local:sheet-of($name as xs:string) as item()? {",
    "  if ($sheets instance of map(*) and map:contains($sheets, $name)) then map:get($sheets, $name) else ()",
    "};",
    "",
    "declare function local:col-letters($letters as xs:string) as xs:integer {",
    "  fold-left(string-to-codepoints(upper-case($letters)), 0, function($n as xs:integer, $cp as xs:integer) as xs:integer {",
    "    $n * 26 + ($cp - 64)",
    "  })",
    "};",
    "",
    "declare function local:sheet-col($sheet as item(), $ref as item()) as xs:integer? {",
    "  let $headers := local:unbox($sheet?headers)",
    "  return typeswitch ($ref)",
    "    case xs:numeric return",
    "      let $i := xs:integer($ref)",
    "      return if ($i ge 0 and $i lt count($headers)) then $i + 1 else ()",
    "    default return",
    "      let $t := string($ref)",
    "      let $named := index-of($headers, $t)",
    "      return if (exists($named)) then $named[1]",
    "        else if (matches($t, \"^[A-Za-z]+$\")) then",
    "          let $n := local:col-letters($t)",
    "          return if ($n ge 1 and $n le count($headers)) then $n else ()",
    "        else if ($t castable as xs:integer) then",
    "          let $i := xs:integer($t)",
    "          return if ($i ge 0 and $i lt count($headers)) then $i + 1 else ()",
    "        else ()",
    "};",
    "",
    "declare function local:sheet-row-map($sheet as item(), $row as item()*) as map(*) {",
    "  let $headers := local:unbox($sheet?headers)",
    "  let $cells := local:unbox($row)",
    "  return map:merge(",
    "    for $h at $i in $headers",
    "    return map:entry(if ($h eq \"\") then string($i - 1) else $h, $cells[$i])",
    "  )",
    "};",
    "",
    "declare function local:sheet-get-cell($name as xs:string, $a1 as xs:string) as item()? {",
    "  let $col := local:col-letters(replace($a1, \"[^A-Za-z]\", \"\"))",
    "  let $row := xs:integer(replace($a1, \"[^0-9]\", \"\"))",
    "  return local:sheet-get-xy($name, $col - 1, $row - 1)",
    "};",
    "",
    "declare function local:sheet-get-xy($name as xs:string, $x as xs:numeric, $y as xs:numeric) as item()? {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then () else",
    "    let $row := local:unbox($sheet?values)[xs:integer($y) + 1]",
    "    return local:unbox($row)[xs:integer($x) + 1]",
    "};",
    "",
    "declare function local:sheet-get-row($name as xs:string, $y as xs:numeric) as item()* {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then () else local:unbox(local:unbox($sheet?values)[xs:integer($y) + 1])",
    "};",
    "",
    "declare function local:sheet-get-column($name as xs:string, $x as xs:numeric) as item()* {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then () else",
    "    for $row in local:unbox($sheet?values) return local:unbox($row)[xs:integer($x) + 1]",
    "};",
    "",
    "declare function local:sheet-get-header($name as xs:string, $x as xs:numeric) as xs:string {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then \"\" else string((local:unbox($sheet?headers)[xs:integer($x) + 1], \"\")[1])",
    "};",
    "",
    "declare function local:sheet-get-data($name as xs:string) as item()* {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then () else local:unbox($sheet?values)",
    "};",
    "",
    "declare function local:sheet-lookup($name as xs:string, $match-col as item(), $match-value as item()*, $return-col as item()*) as item()* {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then () else",
    "  let $mi := local:sheet-col($sheet, $match-col)",
    "  return if (empty($mi)) then () else",
    "  let $matched :=",
    "    for $row in local:unbox($sheet?values)",
    "    let $cells := local:unbox($row)",
    "    where string($cells[$mi]) eq string($match-value)",
    "    return $row",
    "  let $row := $matched[1]",
    "  return if (empty($row)) then ()",
    "    else if (empty($return-col) or string($return-col[1]) eq \"\") then local:sheet-row-map($sheet, $row)",
    "    else",
    "      let $ri := local:sheet-col($sheet, $return-col[1])",
    "      return if (empty($ri)) then () else local:unbox($row)[$ri]",
    "};",
    "",
    "declare function local:decision-table($name as xs:string, $inputs as item()*, $output-col as xs:string?) as item()* {",
    "  let $sheet := local:sheet-of($name)",
    "  return if (empty($sheet)) then () else",
    "  let $headers := local:unbox($sheet?headers)",
    "  let $width := count($headers)",
    "  let $policy := string(($sheet?hitPolicy, \"FIRST\")[1])",
    "  let $join := string(($sheet?collectJoin, \"; \")[1])",
    "  let $inmap := if ($inputs instance of map(*)) then $inputs else map {}",
    "  let $out-idx :=",
    "    if (exists($output-col) and $output-col ne \"\") then (index-of($headers, $output-col)[1], $width)[1]",
    "    else $width",
    "  let $matched :=",
    "    for $row at $y in local:unbox($sheet?values)",
    "    let $cells := local:unbox($row)",
    "    where every $x in 1 to $width satisfies local:decision-cell-ok($sheet, $cells, $inmap, $x, $width)",
    "    return $y",
    "  return if (empty($matched)) then ()",
    "    else if ($policy eq \"UNIQUE\" and count($matched) gt 1) then error(",
    '      QName("http://intehrgrator.local/xquery", "DECISION-UNIQUE"),',
    '      "UNIQUE decision table matched " || count($matched) || " rows: " || $name',
    "    )",
    "    else if ($policy eq \"COLLECT\") then string-join(",
    "      for $y in $matched return string(local:unbox(local:unbox($sheet?values)[$y])[$out-idx]),",
    "      $join",
    "    )",
    "    else local:unbox(local:unbox($sheet?values)[$matched[1]])[$out-idx]",
    "};",
    "",
    "declare function local:decision-cell-ok(",
    "  $sheet as item(), $cells as item()*, $inmap as map(*), $x as xs:integer, $width as xs:integer",
    ") as xs:boolean {",
    "  let $headers := local:unbox($sheet?headers)",
    "  let $meta := local:unbox($sheet?decisionColumns)[$x]",
    "  let $default-role := if ($x eq $width) then \"output\" else \"condition\"",
    "  let $role := if ($meta instance of map(*)) then string(($meta?role, $default-role)[1]) else $default-role",
    "  let $cell := $cells[$x]",
    "  return $role ne \"condition\"",
    "    or string($cell) = (\"\", \"—\", \"–\", \"-\", \"*\")",
    "    or string($cell) eq string((map:get($inmap, $headers[$x]), \"\")[1])",
    "};",
  ];
}

function emitSlot(slot: MappingSlot, env: XqEmitEnv): string[] {
  let exprXq: string;
  try {
    exprXq = emitXQueryExprInner(parseExpression(slot.expression), env);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    exprXq = `(: unparseable expression: ${xqComment(msg)} :) ()`;
  }
  const label = slot.label ?? slot.slotId;
  return [
    `(: ${xqComment(label)} — ${xqComment(slot.expression)} :)`,
    "element slot {",
    `  attribute id { ${xqString(slot.slotId)} },`,
    `  attribute rm-type { ${xqString(slot.rmType)} },`,
    ...(slot.mandatory ? ['  attribute mandatory { "true" },'] : []),
    `  local:as-value(${xqString(slot.rmType)}, ${exprXq})`,
    "}",
  ];
}

/** Map Mapping Expression AST → XQuery 3.1 fragment. */
export function emitXQueryExpr(ast: ExprAst, env: Partial<XqEmitEnv> = {}): string {
  return emitXQueryExprInner(ast, {
    ctx: env.ctx ?? "$source",
    bind: env.bind ?? {},
    warnings: env.warnings ?? [],
  });
}

function emitXQueryExprInner(ast: ExprAst, env: XqEmitEnv): string {
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return xqString(ast.value);
      if (typeof ast.value === "boolean") return ast.value ? "true()" : "false()";
      return String(ast.value);
    case "binary":
      return `(${emitXQueryExprInner(ast.left, env)} ${ast.op} ${emitXQueryExprInner(ast.right, env)})`;
    case "call": {
      if (isQuantifyCall(ast.name)) return emitQuantifierXq(ast, env);
      const args = ast.args.map((a) => emitXQueryExprInner(a, env));
      switch (ast.name) {
        case "trim":
          return `normalize-space(${args[0]})`;
        case "concat":
          return `concat(${args.join(", ")})`;
        case "round":
          return `round(${args[0]})`;
        case "modulo":
          return `(${args[0]} mod ${args[1]})`;
        case "constrain":
          return `(if (${args[0]} lt ${args[1]}) then ${args[1]} else if (${args[0]} gt ${args[2]}) then ${args[2]} else ${args[0]})`;
        case "if":
          return `(if (${args[0]}) then ${args[1]} else ${args[2]})`;
        case "switch":
          return emitSwitchXq(args);
        case "var": {
          const name = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "";
          if (name && env.bind[name]) return `$${env.bind[name]}`;
          if (name && /^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return `$${name}`;
          return `(: unbound var ${xqComment(String(args[0]))} :) ()`;
        }
        case "eq":
          return `deep-equal(${args[0]}, ${args[1]})`;
        case "ne":
          return `not(deep-equal(${args[0]}, ${args[1]}))`;
        case "lt":
          return `(${args[0]} lt ${args[1]})`;
        case "le":
          return `(${args[0]} le ${args[1]})`;
        case "gt":
          return `(${args[0]} gt ${args[1]})`;
        case "ge":
          return `(${args[0]} ge ${args[1]})`;
        case "and":
          return `(${args[0]} and ${args[1]})`;
        case "or":
          return `(${args[0]} or ${args[1]})`;
        case "not":
          return `not(${args[0]})`;
        case "list":
          return `(${args.join(", ")})`;
        case "lists_getIndex":
          return emitListsGetIndexXq(args, ast);
        case "intersection":
          return `(${args[0]}[some $b in ${args[1]} satisfies deep-equal(., $b)])`;
        case "union":
          return `(${args[0]}, ${args[1]}[not(some $a in ${args[0]} satisfies deep-equal(., $a))])`;
        case "difference":
          return `(${args[0]}[not(some $b in ${args[1]} satisfies deep-equal(., $b))])`;
        case "maps_get":
          return emitMapsGetXq(ast, args);
        case "sheet_get_cell":
        case "sheet_get_xy":
        case "sheet_get_row":
        case "sheet_get_column":
        case "sheet_get_header":
        case "sheet_get_data":
        case "sheet_lookup":
        case "decision_table":
          return emitSheetCallXq(ast.name, args);
        case "xpathString":
        case "xpath":
          return emitXPathCall("string-at", ast.args[0], env);
        case "xpathNumber":
          return emitXPathCall("number-at", ast.args[0], env);
        case "xpathBoolean":
          return emitXPathCall("boolean-at", ast.args[0], env);
        case "xpathNode":
          return emitNodePath(ast.args[0], env);
        case "handlebars":
          return args[0] ?? '""';
        case "map":
          return emitMapLiteralXq(ast, args);
        default:
          if (isSheetAccessor(ast.name)) return emitSheetCallXq(ast.name, args);
          return emitXPathCall("string-at", ast.args[0], env);
      }
    }
  }
}

function emitMapsGetXq(ast: Extract<ExprAst, { kind: "call" }>, args: string[]): string {
  const mapArg = ast.args[0];
  const key = args[1] ?? '""';
  if (mapArg?.kind === "literal" && mapArg.value === "defaults") {
    return `map:get($defaults, ${key})`;
  }
  return `(if (${args[0]} eq "defaults") then map:get($defaults, ${key}) else ())`;
}

function emitSheetCallXq(name: string, args: string[]): string {
  const fn = name.replaceAll("_", "-");
  if (name === "decision_table") {
    const output = args.length >= 3 ? args[2]! : "()";
    return `local:decision-table(${args[0] ?? '""'}, ${args[1] ?? "map {}"}, ${output})`;
  }
  if (name === "sheet_lookup") {
    if (args.length >= 4) {
      return `local:sheet-lookup(${args[0]}, ${args[1]}, ${args[2]}, ${args[3]})`;
    }
    return `local:sheet-lookup(${args[0] ?? '""'}, ${args[1] ?? '""'}, ${args[2] ?? '""'}, ())`;
  }
  return `local:${fn}(${args.join(", ")})`;
}

function emitMapLiteralXq(_ast: Extract<ExprAst, { kind: "call" }>, args: string[]): string {
  const entries: string[] = [];
  for (let i = 0; i + 1 < args.length; i += 2) {
    entries.push(`map:entry(${args[i]}, ${args[i + 1]})`);
  }
  if (!entries.length) return "map {}";
  return `map:merge((${entries.join(", ")}))`;
}

function emitListsGetIndexXq(args: string[], ast: Extract<ExprAst, { kind: "call" }>): string {
  const list = `local:unbox(${args[0] ?? "()"})`;
  const where = ast.args[1]?.kind === "literal" ? String(ast.args[1].value) : "";
  if (where === "FIRST" || where === "") return `(${list})[1]`;
  if (where === "LAST") return `(${list})[last()]`;
  const at = args[2] ?? "1";
  if (where === "FROM_END") return `(${list})[last() - (xs:integer(${at}) - 1)]`;
  return `(${list})[xs:integer(${at})]`;
}

function emitQuantifierXq(
  ast: Extract<ExprAst, { kind: "call" }>,
  env: XqEmitEnv,
): string {
  const card = ast.name === "at_least" || ast.name === "at_most" || ast.name === "exactly";
  const list = emitXQueryExprInner(ast.args[0]!, env);
  const n = card ? emitXQueryExprInner(ast.args[1]!, env) : "0";
  const varAst = card ? ast.args[2] : ast.args[1];
  const predAst = card ? ast.args[3] : ast.args[2];
  const varName = varAst?.kind === "literal" ? String(varAst.value) : "item";
  const ident = xqIdent(varName);
  const inner: XqEmitEnv = {
    ctx: `$${ident}`,
    bind: { ...env.bind, [varName]: ident },
    warnings: env.warnings,
  };
  const pred = predAst ? emitXQueryExprInner(predAst, inner) : "true()";
  const counted = `count(for $${ident} in ${list} where ${pred} return $${ident})`;
  switch (ast.name) {
    case "all_of":
      return `(every $${ident} in ${list} satisfies ${pred})`;
    case "any_of":
      return `(some $${ident} in ${list} satisfies ${pred})`;
    case "none_of":
      return `(every $${ident} in ${list} satisfies not(${pred}))`;
    case "at_least":
      return `(${counted} ge ${n})`;
    case "at_most":
      return `(${counted} le ${n})`;
    case "exactly":
      return `(${counted} eq ${n})`;
    default:
      return "false()";
  }
}

function emitXPathCall(
  helper: "string-at" | "number-at" | "boolean-at",
  pathAst: ExprAst | undefined,
  env: XqEmitEnv,
): string {
  if (!pathAst) return "()";
  if (pathAst.kind === "literal" && typeof pathAst.value === "string") {
    const compiled = compileLiteralPath(pathAst.value, helper, env.ctx);
    if (compiled) return compiled;
  } else {
    env.warnings.push(`dynamic source path uses local:${helper}`);
  }
  return `local:${helper}(${env.ctx}, ${emitXQueryExprInner(pathAst, env)})`;
}

function emitNodePath(pathAst: ExprAst | undefined, env: XqEmitEnv): string {
  if (!pathAst) return env.ctx;
  if (pathAst.kind === "literal" && typeof pathAst.value === "string") {
    const compiled = compileSequencePath(pathAst.value.trim(), ctxForPath(pathAst.value.trim(), env.ctx));
    if (compiled) return `local:unbox(${compiled})`;
  } else {
    env.warnings.push("dynamic xpathNode uses local:nodes-at");
  }
  return `local:nodes-at(${env.ctx}, ${emitXQueryExprInner(pathAst, env)})`;
}

function ctxForPath(path: string, relativeCtx: string): string {
  const trimmed = path.trim();
  if (trimmed.startsWith("$") || trimmed.startsWith("/")) return "$source";
  return relativeCtx;
}

/**
 * Compile a fontoxpath-authored literal path to inline XQuery when safe.
 * Falls back to local:*-at helpers for dynamic / complex paths.
 */
export function compileLiteralPath(
  path: string,
  helper: "string-at" | "number-at" | "boolean-at",
  ctxVar = "$source",
): string | null {
  const seq = compileSequencePath(path.trim(), ctxForPath(path, ctxVar));
  if (!seq) return null;
  const cast = helper === "number-at"
    ? "xs:decimal"
    : helper === "boolean-at"
    ? "xs:boolean"
    : "xs:string";
  return `${cast}((${seq})[1])`;
}

/** Sequence (no `[1]` / cast) for loops and xpathNode. */
export function compileSequencePath(path: string, ctxVar = "$source"): string | null {
  const trimmed = path.trim();
  if (!trimmed) return null;

  if (trimmed === "." || trimmed === "./") return ctxVar;
  if (trimmed.startsWith("./")) return `${ctxVar}/${trimmed.slice(2)}`;
  if (trimmed.startsWith("/")) return `$source${trimmed}`;

  if (trimmed.startsWith("$")) {
    return jsonDollarPathToLookup(trimmed, "$source");
  }

  if (trimmed.includes("/")) {
    return `${ctxVar}/${trimmed.replace(/^\.\//, "")}`;
  }

  return jsonDollarPathToLookup(`$.${trimmed.replace(/^\./, "")}`, ctxVar);
}

/** `$.patient.vitals[1].systolic` → `$source?patient?vitals?1?systolic` */
export function jsonDollarPathToLookup(path: string, ctxVar = "$source"): string | null {
  let body = path.trim();
  if (!body.startsWith("$")) return null;
  body = body.slice(1);
  if (body.startsWith(".")) body = body.slice(1);
  if (!body) return ctxVar;

  const segments: string[] = [];
  let i = 0;
  while (i < body.length) {
    if (body[i] === ".") {
      i++;
      continue;
    }
    if (body[i] === "[") {
      const close = body.indexOf("]", i + 1);
      if (close < 0) return null;
      const token = body.slice(i + 1, close);
      if (token === "*") segments.push("*");
      else if (/^\d+$/.test(token)) segments.push(token);
      else if (
        (token.startsWith('"') && token.endsWith('"')) ||
        (token.startsWith("'") && token.endsWith("'"))
      ) {
        segments.push(token.slice(1, -1));
      } else {
        segments.push(token);
      }
      i = close + 1;
      continue;
    }
    let end = i;
    while (end < body.length && !".[".includes(body[end]!)) end++;
    segments.push(body.slice(i, end));
    i = end;
  }

  let expr = ctxVar;
  for (const seg of segments) {
    if (seg === "*") expr += "?*";
    else if (/^\d+$/.test(seg)) expr += `?${seg}`;
    else if (/^[\p{L}_][\p{L}\p{N}_]*$/u.test(seg)) expr += `?${seg}`;
    else expr += `?(${xqString(seg)})`;
  }
  return expr;
}

function emitSwitchXq(args: string[]): string {
  if (args.length < 2) return "()";
  const discriminant = args[0]!;
  const defaultV = args[args.length - 1]!;
  const pairs = args.slice(1, -1);
  let expr = defaultV;
  for (let i = pairs.length - 2; i >= 0; i -= 2) {
    expr = `(if (${discriminant} eq ${pairs[i]}) then ${pairs[i + 1]} else ${expr})`;
  }
  return expr;
}

function xqIdent(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : "item";
}

function indent(text: string, n: number): string {
  const pad = "  ".repeat(n);
  return text.split("\n").map((line) => (line.length ? pad + line : line)).join("\n");
}

function xqString(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function xqComment(value: string): string {
  return value.replace(/:\)/g, ": )");
}
