/**
 * XQuery conversion script language — Mapping Model → self-contained `.xq`.
 *
 * Emits a Model B slot-manifest program: each Blockly-mapped slot becomes an
 * XQuery binding with typed DV_* XML constructors. `for_each_source` /
 * `for_each_list` compile to `for $var in … return` iteration over loop-scoped
 * slots. Full COMPOSITION nesting remains a follow-up once skeleton metadata is
 * available at export time.
 *
 * See docs/future/xquery-export-investigation.md.
 */
import type {
  MappingLoop,
  MappingModel,
  MappingSlot,
  TargetSignatureNode,
} from "../../types/mod.ts";
import { expressionUsesRelativeSourcePath } from "../mapping_model/loops.ts";
import { parseExpression, type ExprAst, isQuantifyCall } from "../expression/mod.ts";

export class XQueryExportError extends Error {
  override name = "XQueryExportError";
}

export interface XQueryEmitEnv {
  bind?: Record<string, string>;
  /** Context node for xpath* — defaults to `$source`; loop bodies use the loop var. */
  sourceVar?: string;
}

const SHEET_ACCESSOR_RE =
  /\b(sheet_get_(?:cell|xy|row|column|header|data)|sheet_lookup|decision_table)\s*\(/;

export function generateXQuery(model: MappingModel): string {
  validateExportModel(model);

  const loops = model.loops ?? [];
  const { loopSlots, topLevelSlots } = partitionSlots(model.slots, loops, model.targetSignature);

  const loopBlocks = loops.map((loop) =>
    emitLoop(loop, loopSlots.get(loop.attachSlotId) ?? []).map((line) => `    ${line}`).join("\n")
  );
  const slotBlocks = topLevelSlots.map((slot) =>
    emitSlot(slot).map((line) => `    ${line}`).join("\n")
  );

  const lines: string[] = [
    'xquery version "3.1";',
    "",
    "(: Generated by intEHRgrator — Conversion Script (XQuery) :)",
    `(: Target: ${xqComment(model.templateId)} :)`,
    `(: Target instance format: ${xqComment(model.targetFormat ?? "openehr-template")} :)`,
    "(: Runtime: Saxon / BaseX / eXist — bind external $source to XML node or XPath 3.1 map :)",
    "(: Output: mapping-result slot manifest (Model B). Validate assembled Composition with Archie OPT. :)",
    "(: In-app Test Run continues to use Mapping Model + Target instance format — not this .xq. :)",
    "",
    'declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";',
    'declare namespace rm = "http://schemas.openehr.org/v1";',
    'declare namespace xsi = "http://www.w3.org/2001/XMLSchema-instance";',
    "",
    'declare option output:method "xml";',
    'declare option output:indent "yes";',
    "",
    "declare variable $source external;",
    "declare variable $defaults as map(*) external := map {};",
    "",
    ...emitHelpers(),
    "",
    "declare function local:convert($source as item()*) as element(mapping-result) {",
    "  element mapping-result {",
    `    attribute template { ${xqString(model.templateId)} }${
      loopBlocks.length || slotBlocks.length ? "," : ""
    }`,
  ];

  if (loopBlocks.length) {
    lines.push("    element loops {");
    for (let i = 0; i < loopBlocks.length; i++) {
      const block = loopBlocks[i]!;
      const comma = i < loopBlocks.length - 1 ? "," : slotBlocks.length ? "," : "";
      lines.push(block + comma);
    }
    lines.push("    }" + (slotBlocks.length ? "," : ""));
  }

  if (!slotBlocks.length && !loopBlocks.length) {
    lines.push(
      "    (: no mapped slots — map Target value slots in Blockly, then re-export :)",
    );
  } else if (slotBlocks.length) {
    lines.push("    element slots {");
    for (let i = 0; i < slotBlocks.length; i++) {
      const block = slotBlocks[i]!;
      const comma = i < slotBlocks.length - 1 ? "," : "";
      lines.push(block + comma);
    }
    lines.push("    }");
  }

  lines.push(
    "  }",
    "};",
    "",
    "local:convert($source)",
    "",
  );
  return lines.join("\n");
}

function validateExportModel(model: MappingModel): void {
  for (const block of model.unsupported ?? []) {
    if (block.reason === "removed") {
      throw new XQueryExportError(
        `Cannot export XQuery: Blockly block type "${block.blockType}" was removed from the ` +
          "verifiable mapping subset (#35). Remove it from the canvas before exporting.",
      );
    }
  }

  for (const slot of model.slots) {
    if (SHEET_ACCESSOR_RE.test(slot.expression)) {
      throw new XQueryExportError(
        `Cannot export XQuery: slot "${slot.slotId}" uses Sheet accessors ` +
          `(${slot.expression}). Bind a $sheets map at runtime or remove Sheet lookups before export.`,
      );
    }
  }
}

function partitionSlots(
  slots: MappingSlot[],
  loops: MappingLoop[],
  signature?: TargetSignatureNode[],
): { loopSlots: Map<string, MappingSlot[]>; topLevelSlots: MappingSlot[] } {
  const loopSlots = new Map<string, MappingSlot[]>();
  for (const loop of loops) {
    loopSlots.set(loop.attachSlotId, []);
  }

  const topLevelSlots: MappingSlot[] = [];
  for (const slot of slots) {
    if (!expressionUsesRelativeSourcePath(slot.expression)) {
      topLevelSlots.push(slot);
      continue;
    }
    const loop = resolveLoopForSlot(slot, loops, signature);
    if (!loop) {
      topLevelSlots.push(slot);
      continue;
    }
    const bucket = loopSlots.get(loop.attachSlotId) ?? [];
    bucket.push(slot);
    loopSlots.set(loop.attachSlotId, bucket);
  }

  return { loopSlots, topLevelSlots };
}

function resolveLoopForSlot(
  slot: MappingSlot,
  loops: MappingLoop[],
  signature?: TargetSignatureNode[],
): MappingLoop | undefined {
  const relativeLoops = loops.filter((loop) => slotMatchesLoop(slot.slotId, loop, signature));
  if (relativeLoops.length === 1) return relativeLoops[0];
  if (relativeLoops.length > 1) {
    return relativeLoops.find((loop) => {
      const ids = signatureSlotIds(loop.attachSlotId, signature);
      return ids?.has(slot.slotId);
    }) ?? relativeLoops[0];
  }
  return loops.length === 1 ? loops[0] : undefined;
}

function slotMatchesLoop(
  slotId: string,
  loop: MappingLoop,
  signature?: TargetSignatureNode[],
): boolean {
  const ids = signatureSlotIds(loop.attachSlotId, signature);
  if (ids) return ids.has(slotId);
  return slotId === loop.attachSlotId ||
    slotId.startsWith(`${loop.attachSlotId}/`) ||
    slotId.startsWith(`${loop.attachSlotId}//`);
}

function signatureSlotIds(
  attachSlotId: string,
  signature?: TargetSignatureNode[],
): Set<string> | undefined {
  if (!signature?.length) return undefined;
  const node = findSignatureNode(signature, attachSlotId);
  if (!node) return undefined;
  return new Set(collectSignatureSlotIds(node));
}

function findSignatureNode(
  nodes: TargetSignatureNode[],
  slotId: string,
): TargetSignatureNode | undefined {
  for (const node of nodes) {
    if (node.slotId === slotId) return node;
    const nested = findSignatureNode(node.children, slotId);
    if (nested) return nested;
  }
  return undefined;
}

function collectSignatureSlotIds(node: TargetSignatureNode): string[] {
  const ids = [node.slotId];
  for (const child of node.children) {
    ids.push(...collectSignatureSlotIds(child));
  }
  return ids;
}

function emitLoop(loop: MappingLoop, slots: MappingSlot[]): string[] {
  const ident = loopVarIdent(loop.varName);
  const sequence = compileLoopSequence(loop);
  const env: XQueryEmitEnv = {
    sourceVar: `$${ident}`,
    bind: { [loop.varName]: ident },
  };

  const attrs = [
    `attribute attach-slot-id { ${xqString(loop.attachSlotId)} }`,
    `attribute var-name { ${xqString(loop.varName)} }`,
    `attribute kind { ${xqString(loop.kind ?? "source")} }`,
  ];
  if (loop.path) attrs.push(`attribute path { ${xqString(loop.path)} }`);
  if (loop.collection) attrs.push(`attribute collection { ${xqString(loop.collection)} }`);

  const slotLines: string[] = [];
  if (slots.length) {
    slotLines.push("  element slots {");
    for (let i = 0; i < slots.length; i++) {
      const block = emitSlot(slots[i]!, env).map((line) => `    ${line}`).join("\n");
      const comma = i < slots.length - 1 ? "," : "";
      slotLines.push(block + comma);
    }
    slotLines.push("  }");
  }

  const body = [
    "element loop {",
    ...attrs.map((line, index) => `  ${line}${index < attrs.length - 1 || slotLines.length ? "," : ""}`),
    ...slotLines,
    "}",
  ];

  return [
    `for $${ident} in ${sequence}`,
    "return",
    ...body.map((line) => `  ${line}`),
  ];
}

function loopVarIdent(varName: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(varName) ? varName : "item";
}

/** Compile a loop collection path to an XQuery sequence expression. */
export function compileLoopSequence(loop: MappingLoop): string {
  if (loop.kind === "list") {
    if (!loop.collection) {
      return "(: for_each_list without collection expression :) ()";
    }
    return emitXQueryExpr(parseExpression(loop.collection));
  }

  const path = loop.path.trim();
  if (!path) {
    return "(: for_each_source without PATH :) ()";
  }

  if (path.startsWith("$.")) {
    const base = path.replace(/\[\*\]$/, "");
    const lookup = jsonDollarPathToLookup(base);
    if (lookup) {
      return `local:iterable-sequence(${lookup})`;
    }
    return `local:lookup-sequence($source, ${xqString(path)})`;
  }

  if (path.startsWith("/")) {
    return `$source${path}`;
  }

  return `local:lookup-sequence($source, ${xqString(path)})`;
}

function emitHelpers(): string[] {
  return [
    "(: --- Source access (fontoxpath-authored paths → XQuery 3.1) --- :)",
    "",
    "declare function local:iterable-sequence($nodes as item()*) as item()* {",
    "  if ($nodes instance of array(*)) then $nodes?*",
    "  else $nodes",
    "};",
    "",
    "declare function local:lookup-sequence($ctx as item()*, $path as xs:string) as item()* {",
    "  (: Dynamic or non-literal loop paths — prefer compile-time $. / / paths from export :) ",
    "  if (starts-with($path, \"$\"))",
    "  then let $nodes := local:json-lookup($ctx, $path)",
    "       return if ($nodes instance of array(*)) then $nodes?* else $nodes",
    "  else error(",
    '    QName("http://intehrgrator.local/xquery", "DYNAMIC-LOOP-PATH"),',
    '    "Prefer compile-time literal loop PATH from intEHRgrator export; got: " || $path',
    "  )",
    "};",
    "",
    "declare function local:string-at($ctx as item()*, $path as xs:string) as xs:string? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:string($value)",
    "};",
    "",
    "declare function local:number-at($ctx as item()*, $path as xs:string) as xs:decimal? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:decimal($value)",
    "};",
    "",
    "declare function local:boolean-at($ctx as item()*, $path as xs:string) as xs:boolean? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:boolean($value)",
    "};",
    "",
    "declare function local:lookup($ctx as item()*, $path as xs:string) as item()* {",
    "  if (starts-with($path, \"$\"))",
    "  then local:json-lookup($ctx, $path)",
    "  else error(",
    '    QName("http://intehrgrator.local/xquery", "DYNAMIC-XML-PATH"),',
    '    "Prefer compile-time literal XML paths from intEHRgrator export; got: " || $path',
    "  )",
    "};",
    "",
    "declare function local:json-lookup($ctx as item()*, $path as xs:string) as item()* {",
    "  let $body := replace(replace($path, \"^\\\\$\\\\.?\", \"\"), \"\\\\[(\\\\d+)\\\\]\", \".$1\")",
    "  let $segments := tokenize($body, \"\\\\.\")[. ne \"\"]",
    "  return fold-left(",
    "    $segments,",
    "    $ctx,",
    "    function($acc as item()*, $seg as xs:string) as item()* {",
    "      if (empty($acc)) then ()",
    "      else if ($seg castable as xs:integer) then $acc[xs:integer($seg)]",
    "      else $acc?($seg)",
    "    }",
    "  )",
    "};",
    "",
    "(: --- DV_* constructors (RM XML) --- :)",
    "",
    "declare function local:dv-text($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_TEXT" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-coded-text($value as xs:string?, $code as xs:string?, $terminology as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_CODED_TEXT" },',
    "    element rm:value { $value },",
    "    element rm:defining_code {",
    "      element rm:terminology_id { element rm:value { $terminology } },",
    "      element rm:code_string { $code }",
    "    }",
    "  }",
    "};",
    "",
    "declare function local:dv-quantity($magnitude as xs:decimal?, $units as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_QUANTITY" },',
    "    element rm:magnitude { $magnitude },",
    "    element rm:units { $units }",
    "  }",
    "};",
    "",
    "declare function local:dv-count($magnitude as xs:integer?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_COUNT" },',
    "    element rm:magnitude { $magnitude }",
    "  }",
    "};",
    "",
    "declare function local:dv-boolean($value as xs:boolean?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_BOOLEAN" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-date-time($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_DATE_TIME" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-uri($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_URI" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:as-value($rm-type as xs:string, $value as item()*) as element()* {",
    "  switch ($rm-type)",
    '    case "DV_QUANTITY" return local:dv-quantity(($value)[1] ! xs:decimal(.), ())',
    '    case "DV_COUNT" return local:dv-count(($value)[1] ! xs:integer(.))',
    '    case "DV_INTEGER" return local:dv-count(($value)[1] ! xs:integer(.))',
    '    case "DV_BOOLEAN" return local:dv-boolean(($value)[1] ! xs:boolean(.))',
    '    case "DV_DATE_TIME" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_DATE" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_TIME" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_URI" return local:dv-uri(($value)[1] ! xs:string(.))',
    '    case "DV_EHR_URI" return local:dv-uri(($value)[1] ! xs:string(.))',
    '    case "DV_CODED_TEXT" return local:dv-coded-text(($value)[1] ! xs:string(.), (), ())',
    "    default return local:dv-text(($value)[1] ! xs:string(.))",
    "};",
  ];
}

function emitSlot(slot: MappingSlot, env: XQueryEmitEnv = {}): string[] {
  let exprXq: string;
  try {
    exprXq = emitXQueryExpr(parseExpression(slot.expression), env);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    exprXq = `(: unparseable expression: ${xqComment(msg)} :) ()`;
  }
  const label = slot.label ?? slot.slotId;
  return [
    `(: ${xqComment(label)} — ${xqComment(slot.expression)} :)`,
    "element slot {",
    `  attribute id { ${xqString(slot.slotId)} },`,
    `  attribute rm-type { ${xqString(slot.rmType)} },`,
    ...(slot.mandatory ? ['  attribute mandatory { "true" },'] : []),
    `  local:as-value(${xqString(slot.rmType)}, ${exprXq})`,
    "}",
  ];
}

/** Map Mapping Expression AST → XQuery 3.1 fragment (context variable `$source`). */
export function emitXQueryExpr(ast: ExprAst, env: XQueryEmitEnv = {}): string {
  const sourceVar = env.sourceVar ?? "$source";
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return xqString(ast.value);
      if (typeof ast.value === "boolean") return ast.value ? "true()" : "false()";
      return String(ast.value);
    case "binary":
      return `(${emitXQueryExpr(ast.left, env)} ${ast.op} ${emitXQueryExpr(ast.right, env)})`;
    case "call": {
      if (isQuantifyCall(ast.name)) return emitQuantifierXq(ast, env);
      const args = ast.args.map((a) => emitXQueryExpr(a, env));
      switch (ast.name) {
        case "trim":
          return `normalize-space(${args[0]})`;
        case "concat":
          return `concat(${args.join(", ")})`;
        case "round":
          return `round(${args[0]})`;
        case "modulo":
          return `(${args[0]} mod ${args[1]})`;
        case "constrain":
          return `(if (${args[0]} lt ${args[1]}) then ${args[1]} else if (${args[0]} gt ${args[2]}) then ${args[2]} else ${args[0]})`;
        case "if":
          return `(if (${args[0]}) then ${args[1]} else ${args[2]})`;
        case "switch":
          return emitSwitchXq(args);
        case "var": {
          const name = ast.args[0]?.kind === "literal" ? String(ast.args[0].value) : "";
          if (name && env.bind?.[name]) return `$${env.bind[name]}`;
          return `$vars(${args[0]})`;
        }
        case "eq":
          return `deep-equal(${args[0]}, ${args[1]})`;
        case "ne":
          return `not(deep-equal(${args[0]}, ${args[1]}))`;
        case "lt":
          return `(${args[0]} lt ${args[1]})`;
        case "le":
          return `(${args[0]} le ${args[1]})`;
        case "gt":
          return `(${args[0]} gt ${args[1]})`;
        case "ge":
          return `(${args[0]} ge ${args[1]})`;
        case "and":
          return `(${args[0]} and ${args[1]})`;
        case "or":
          return `(${args[0]} or ${args[1]})`;
        case "not":
          return `not(${args[0]})`;
        case "list":
          return `(${args.join(", ")})`;
        case "intersection":
          return `(${args[0]}[some $b in ${args[1]} satisfies deep-equal(., $b)])`;
        case "union":
          return `(${args[0]}, ${args[1]}[not(some $a in ${args[0]} satisfies deep-equal(., $a))])`;
        case "difference":
          return `(${args[0]}[not(some $b in ${args[1]} satisfies deep-equal(., $b))])`;
        case "maps_get":
          return `(if (${args[0]} eq "defaults") then map:get($defaults, ${args[1]}) else ())`;
        case "sheet_get_cell":
        case "sheet_get_xy":
        case "sheet_get_row":
        case "sheet_get_column":
        case "sheet_get_header":
        case "sheet_get_data":
        case "sheet_lookup":
          throw new XQueryExportError(
            `${ast.name} requires a $sheets map binding — export validation should have caught this`,
          );
        case "decision_table":
          throw new XQueryExportError(
            "decision_table requires Sheet/runtime evaluation — not supported in XQuery export",
          );
        case "xpathString":
        case "xpath":
          return emitXPathCall("string-at", ast.args[0], env);
        case "xpathNumber":
          return emitXPathCall("number-at", ast.args[0], env);
        case "xpathBoolean":
          return emitXPathCall("boolean-at", ast.args[0], env);
        case "xpathNode":
          if (ast.args[0]?.kind === "literal" && typeof ast.args[0].value === "string") {
            const path = ast.args[0].value.trim();
            if (path.startsWith("/")) return `(${sourceVar}${path})[1]`;
            const lookup = compileRelativeLookup(path, sourceVar);
            if (lookup) return `(${lookup})[1]`;
          }
          return sourceVar;
        case "handlebars":
          return args[0] ?? '""';
        case "map":
          return "map {}";
        default:
          return emitXPathCall("string-at", ast.args[0], env);
      }
    }
  }
}

function emitQuantifierXq(
  ast: Extract<ExprAst, { kind: "call" }>,
  env: XQueryEmitEnv,
): string {
  const card = ast.name === "at_least" || ast.name === "at_most" || ast.name === "exactly";
  const list = emitXQueryExpr(ast.args[0]!, env);
  const n = card ? emitXQueryExpr(ast.args[1]!, env) : "0";
  const varAst = card ? ast.args[2] : ast.args[1];
  const predAst = card ? ast.args[3] : ast.args[2];
  const varName = varAst?.kind === "literal" ? String(varAst.value) : "item";
  const ident = /^[A-Za-z_][A-Za-z0-9_]*$/.test(varName) ? varName : "item";
  const inner = { ...env, bind: { ...env.bind, [varName]: ident } };
  const pred = predAst ? emitXQueryExpr(predAst, inner) : "true()";
  const counted = `count(for $${ident} in ${list} where ${pred} return $${ident})`;
  switch (ast.name) {
    case "all_of":
      return `(every $${ident} in ${list} satisfies ${pred})`;
    case "any_of":
      return `(some $${ident} in ${list} satisfies ${pred})`;
    case "none_of":
      return `(every $${ident} in ${list} satisfies not(${pred}))`;
    case "at_least":
      return `(${counted} ge ${n})`;
    case "at_most":
      return `(${counted} le ${n})`;
    case "exactly":
      return `(${counted} eq ${n})`;
    default:
      return "false()";
  }
}

function emitXPathCall(
  helper: "string-at" | "number-at" | "boolean-at",
  pathAst: ExprAst | undefined,
  env: XQueryEmitEnv,
): string {
  const sourceVar = env.sourceVar ?? "$source";
  if (!pathAst) return "()";
  if (pathAst.kind === "literal" && typeof pathAst.value === "string") {
    const compiled = compileLiteralPath(pathAst.value, helper, sourceVar);
    if (compiled) return compiled;
  }
  return `local:${helper}(${sourceVar}, ${emitXQueryExpr(pathAst, env)})`;
}

/**
 * Compile a fontoxpath-authored literal path to inline XQuery when safe.
 * Falls back to local:*-at helpers for dynamic / complex paths.
 */
export function compileLiteralPath(
  path: string,
  helper: "string-at" | "number-at" | "boolean-at",
  sourceVar = "$source",
): string | null {
  const trimmed = path.trim();
  if (!trimmed) return null;

  const cast = helper === "number-at"
    ? "xs:decimal"
    : helper === "boolean-at"
    ? "xs:boolean"
    : "xs:string";

  if (trimmed === "." || trimmed === "./") {
    return `${cast}((${sourceVar})[1])`;
  }
  if (trimmed.startsWith("./")) {
    return `${cast}((${sourceVar}/${trimmed.slice(2)})[1])`;
  }
  if (trimmed.startsWith("/")) {
    return `${cast}((${sourceVar}${trimmed})[1])`;
  }

  if (trimmed.startsWith("$")) {
    const lookup = jsonDollarPathToLookup(trimmed, sourceVar);
    if (!lookup) return null;
    return `${cast}((${lookup})[1])`;
  }

  const relative = compileRelativeLookup(trimmed, sourceVar);
  if (relative) return `${cast}((${relative})[1])`;

  return null;
}

function compileRelativeLookup(path: string, sourceVar: string): string | null {
  const trimmed = path.trim();
  if (!trimmed || trimmed.startsWith("$") || trimmed.startsWith("/")) return null;
  if (trimmed === "." || trimmed === "./") return sourceVar;

  const body = trimmed.replace(/^\.\//, "");
  const segments: string[] = [];
  let i = 0;
  while (i < body.length) {
    if (body[i] === ".") {
      i++;
      continue;
    }
    if (body[i] === "[") {
      const close = body.indexOf("]", i + 1);
      if (close < 0) return null;
      const token = body.slice(i + 1, close);
      if (/^\d+$/.test(token)) segments.push(token);
      else return null;
      i = close + 1;
      continue;
    }
    let end = i;
    while (end < body.length && !".[".includes(body[end]!)) end++;
    segments.push(body.slice(i, end));
    i = end;
  }

  let expr = sourceVar;
  for (const seg of segments) {
    if (/^\d+$/.test(seg)) expr += `[${seg}]`;
    else if (/^[\p{L}_][\p{L}\p{N}_]*$/u.test(seg)) expr += `?${seg}`;
    else expr += `?(${xqString(seg)})`;
  }
  return expr;
}

/** `$.patient.vitals[1].systolic` → `$source?patient?vitals?1?systolic` */
export function jsonDollarPathToLookup(path: string, root = "$source"): string | null {
  let body = path.trim();
  if (!body.startsWith("$")) return null;
  body = body.slice(1);
  if (body.startsWith(".")) body = body.slice(1);
  if (!body) return root;

  const segments: string[] = [];
  let i = 0;
  while (i < body.length) {
    if (body[i] === ".") {
      i++;
      continue;
    }
    if (body[i] === "[") {
      const close = body.indexOf("]", i + 1);
      if (close < 0) return null;
      const token = body.slice(i + 1, close);
      if (/^\d+$/.test(token)) segments.push(token);
      else if (
        (token.startsWith('"') && token.endsWith('"')) ||
        (token.startsWith("'") && token.endsWith("'"))
      ) {
        segments.push(token.slice(1, -1));
      } else {
        segments.push(token);
      }
      i = close + 1;
      continue;
    }
    let end = i;
    while (end < body.length && !".[".includes(body[end]!)) end++;
    segments.push(body.slice(i, end));
    i = end;
  }

  let expr = root;
  for (const seg of segments) {
    if (/^\d+$/.test(seg)) expr += `?${seg}`;
    else if (/^[\p{L}_][\p{L}\p{N}_]*$/u.test(seg)) expr += `?${seg}`;
    else expr += `?(${xqString(seg)})`;
  }
  return expr;
}

function emitSwitchXq(args: string[]): string {
  if (args.length < 2) return "()";
  const discriminant = args[0]!;
  const defaultV = args[args.length - 1]!;
  const pairs = args.slice(1, -1);
  let expr = defaultV;
  for (let i = pairs.length - 2; i >= 0; i -= 2) {
    expr = `(if (${discriminant} eq ${pairs[i]}) then ${pairs[i + 1]} else ${expr})`;
  }
  return expr;
}

function xqString(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function xqComment(value: string): string {
  return value.replace(/:\)/g, ": )");
}
