/**
 * XQuery conversion script language — Mapping Model → self-contained `.xq`.
 *
 * Emits a Model B slot-manifest program: each Blockly-mapped slot becomes an
 * XQuery binding with typed DV_* XML constructors. Full COMPOSITION nesting
 * remains a follow-up once skeleton metadata is available at export time.
 *
 * See docs/future/xquery-export-investigation.md.
 */
import type { MappingModel, MappingSlot } from "../../types/mod.ts";
import { parseExpression, type ExprAst } from "../expression/mod.ts";

export function generateXQuery(model: MappingModel): string {
  const slotBlocks = model.slots.map((slot) =>
    emitSlot(slot).map((line) => `    ${line}`).join("\n")
  );

  const lines: string[] = [
    'xquery version "3.1";',
    "",
    "(: Generated by intEHRgrator — Conversion Script (XQuery) :)",
    `(: Target: ${xqComment(model.templateId)} :)`,
    `(: Target instance format: ${xqComment(model.targetFormat ?? "openehr-template")} :)`,
    "(: Runtime: Saxon / BaseX / eXist — bind external $source to XML node or XPath 3.1 map :)",
    "(: Output: mapping-result slot manifest (Model B). Validate assembled Composition with Archie OPT. :)",
    "(: In-app Test Run continues to use Mapping Model + Target instance format — not this .xq. :)",
    "",
    'declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";',
    'declare namespace rm = "http://schemas.openehr.org/v1";',
    'declare namespace xsi = "http://www.w3.org/2001/XMLSchema-instance";',
    "",
    'declare option output:method "xml";',
    'declare option output:indent "yes";',
    "",
    "declare variable $source external;",
    "",
    ...emitHelpers(),
    "",
    "declare function local:convert($source as item()*) as element(mapping-result) {",
    "  element mapping-result {",
    `    attribute template { ${xqString(model.templateId)} }${
      slotBlocks.length ? "," : ""
    }`,
  ];

  if (!slotBlocks.length) {
    lines.push(
      "    (: no mapped slots — map Target value slots in Blockly, then re-export :)",
    );
  } else {
    for (let i = 0; i < slotBlocks.length; i++) {
      const block = slotBlocks[i]!;
      const comma = i < slotBlocks.length - 1 ? "," : "";
      lines.push(block + comma);
    }
  }

  lines.push(
    "  }",
    "};",
    "",
    "local:convert($source)",
    "",
  );
  return lines.join("\n");
}

function emitHelpers(): string[] {
  return [
    "(: --- Source access (fontoxpath-authored paths → XQuery 3.1) --- :)",
    "",
    "declare function local:string-at($ctx as item()*, $path as xs:string) as xs:string? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:string($value)",
    "};",
    "",
    "declare function local:number-at($ctx as item()*, $path as xs:string) as xs:decimal? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:decimal($value)",
    "};",
    "",
    "declare function local:boolean-at($ctx as item()*, $path as xs:string) as xs:boolean? {",
    "  let $value := local:lookup($ctx, $path)",
    "  return if (empty($value)) then () else xs:boolean($value)",
    "};",
    "",
    "declare function local:lookup($ctx as item()*, $path as xs:string) as item()* {",
    "  if (starts-with($path, \"$\"))",
    "  then local:json-lookup($ctx, $path)",
    "  else error(",
    '    QName("http://intehrgrator.local/xquery", "DYNAMIC-XML-PATH"),',
    '    "Prefer compile-time literal XML paths from intEHRgrator export; got: " || $path',
    "  )",
    "};",
    "",
    "declare function local:json-lookup($ctx as item()*, $path as xs:string) as item()* {",
    "  let $body := replace(replace($path, \"^\\\\$\\\\.?\", \"\"), \"\\\\[(\\\\d+)\\\\]\", \".$1\")",
    "  let $segments := tokenize($body, \"\\\\.\")[. ne \"\"]",
    "  return fold-left(",
    "    $segments,",
    "    $ctx,",
    "    function($acc as item()*, $seg as xs:string) as item()* {",
    "      if (empty($acc)) then ()",
    "      else if ($seg castable as xs:integer) then $acc[xs:integer($seg)]",
    "      else $acc?($seg)",
    "    }",
    "  )",
    "};",
    "",
    "(: --- DV_* constructors (RM XML) --- :)",
    "",
    "declare function local:dv-text($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_TEXT" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-coded-text($value as xs:string?, $code as xs:string?, $terminology as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_CODED_TEXT" },',
    "    element rm:value { $value },",
    "    element rm:defining_code {",
    "      element rm:terminology_id { element rm:value { $terminology } },",
    "      element rm:code_string { $code }",
    "    }",
    "  }",
    "};",
    "",
    "declare function local:dv-quantity($magnitude as xs:decimal?, $units as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_QUANTITY" },',
    "    element rm:magnitude { $magnitude },",
    "    element rm:units { $units }",
    "  }",
    "};",
    "",
    "declare function local:dv-count($magnitude as xs:integer?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_COUNT" },',
    "    element rm:magnitude { $magnitude }",
    "  }",
    "};",
    "",
    "declare function local:dv-boolean($value as xs:boolean?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_BOOLEAN" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-date-time($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_DATE_TIME" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:dv-uri($value as xs:string?) as element(rm:value) {",
    "  element rm:value {",
    '    attribute xsi:type { "DV_URI" },',
    "    element rm:value { $value }",
    "  }",
    "};",
    "",
    "declare function local:as-value($rm-type as xs:string, $value as item()*) as element()* {",
    "  switch ($rm-type)",
    '    case "DV_QUANTITY" return local:dv-quantity(($value)[1] ! xs:decimal(.), ())',
    '    case "DV_COUNT" return local:dv-count(($value)[1] ! xs:integer(.))',
    '    case "DV_INTEGER" return local:dv-count(($value)[1] ! xs:integer(.))',
    '    case "DV_BOOLEAN" return local:dv-boolean(($value)[1] ! xs:boolean(.))',
    '    case "DV_DATE_TIME" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_DATE" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_TIME" return local:dv-date-time(($value)[1] ! xs:string(.))',
    '    case "DV_URI" return local:dv-uri(($value)[1] ! xs:string(.))',
    '    case "DV_EHR_URI" return local:dv-uri(($value)[1] ! xs:string(.))',
    '    case "DV_CODED_TEXT" return local:dv-coded-text(($value)[1] ! xs:string(.), (), ())',
    "    default return local:dv-text(($value)[1] ! xs:string(.))",
    "};",
  ];
}

function emitSlot(slot: MappingSlot): string[] {
  let exprXq: string;
  try {
    exprXq = emitXQueryExpr(parseExpression(slot.expression));
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    exprXq = `(: unparseable expression: ${xqComment(msg)} :) ()`;
  }
  const label = slot.label ?? slot.slotId;
  return [
    `(: ${xqComment(label)} — ${xqComment(slot.expression)} :)`,
    "element slot {",
    `  attribute id { ${xqString(slot.slotId)} },`,
    `  attribute rm-type { ${xqString(slot.rmType)} },`,
    ...(slot.mandatory ? ['  attribute mandatory { "true" },'] : []),
    `  local:as-value(${xqString(slot.rmType)}, ${exprXq})`,
    "}",
  ];
}

/** Map Mapping Expression AST → XQuery 3.1 fragment (context variable `$source`). */
export function emitXQueryExpr(ast: ExprAst): string {
  switch (ast.kind) {
    case "literal":
      if (typeof ast.value === "string") return xqString(ast.value);
      if (typeof ast.value === "boolean") return ast.value ? "true()" : "false()";
      return String(ast.value);
    case "binary":
      return `(${emitXQueryExpr(ast.left)} ${ast.op} ${emitXQueryExpr(ast.right)})`;
    case "call": {
      const args = ast.args.map(emitXQueryExpr);
      switch (ast.name) {
        case "trim":
          return `normalize-space(${args[0]})`;
        case "concat":
          return `concat(${args.join(", ")})`;
        case "if":
          return `(if (${args[0]}) then ${args[1]} else ${args[2]})`;
        case "switch":
          return emitSwitchXq(args);
        case "var":
          return `$vars(${args[0]})`;
        case "xpathString":
        case "xpath":
          return emitXPathCall("string-at", ast.args[0]);
        case "xpathNumber":
          return emitXPathCall("number-at", ast.args[0]);
        case "xpathBoolean":
          return emitXPathCall("boolean-at", ast.args[0]);
        default:
          return emitXPathCall("string-at", ast.args[0]);
      }
    }
  }
}

function emitXPathCall(
  helper: "string-at" | "number-at" | "boolean-at",
  pathAst: ExprAst | undefined,
): string {
  if (!pathAst) return "()";
  if (pathAst.kind === "literal" && typeof pathAst.value === "string") {
    const compiled = compileLiteralPath(pathAst.value, helper);
    if (compiled) return compiled;
  }
  return `local:${helper}($source, ${emitXQueryExpr(pathAst)})`;
}

/**
 * Compile a fontoxpath-authored literal path to inline XQuery when safe.
 * Falls back to local:*-at helpers for dynamic / complex paths.
 */
export function compileLiteralPath(
  path: string,
  helper: "string-at" | "number-at" | "boolean-at",
): string | null {
  const trimmed = path.trim();
  if (!trimmed) return null;

  const cast = helper === "number-at"
    ? "xs:decimal"
    : helper === "boolean-at"
    ? "xs:boolean"
    : "xs:string";

  if (trimmed === "." || trimmed === "./") {
    return `${cast}(($source)[1])`;
  }
  if (trimmed.startsWith("./")) {
    return `${cast}(($source/${trimmed.slice(2)})[1])`;
  }
  if (trimmed.startsWith("/")) {
    return `${cast}(($source${trimmed})[1])`;
  }

  if (trimmed.startsWith("$")) {
    const lookup = jsonDollarPathToLookup(trimmed);
    if (!lookup) return null;
    return `${cast}((${lookup})[1])`;
  }

  return null;
}

/** `$.patient.vitals[1].systolic` → `$source?patient?vitals?1?systolic` */
export function jsonDollarPathToLookup(path: string): string | null {
  let body = path.trim();
  if (!body.startsWith("$")) return null;
  body = body.slice(1);
  if (body.startsWith(".")) body = body.slice(1);
  if (!body) return "$source";

  const segments: string[] = [];
  let i = 0;
  while (i < body.length) {
    if (body[i] === ".") {
      i++;
      continue;
    }
    if (body[i] === "[") {
      const close = body.indexOf("]", i + 1);
      if (close < 0) return null;
      const token = body.slice(i + 1, close);
      if (/^\d+$/.test(token)) segments.push(token);
      else if (
        (token.startsWith('"') && token.endsWith('"')) ||
        (token.startsWith("'") && token.endsWith("'"))
      ) {
        segments.push(token.slice(1, -1));
      } else {
        segments.push(token);
      }
      i = close + 1;
      continue;
    }
    let end = i;
    while (end < body.length && !".[".includes(body[end]!)) end++;
    segments.push(body.slice(i, end));
    i = end;
  }

  let expr = "$source";
  for (const seg of segments) {
    if (/^\d+$/.test(seg)) expr += `?${seg}`;
    else if (/^[\p{L}_][\p{L}\p{N}_]*$/u.test(seg)) expr += `?${seg}`;
    else expr += `?(${xqString(seg)})`;
  }
  return expr;
}

function emitSwitchXq(args: string[]): string {
  if (args.length < 2) return "()";
  const discriminant = args[0]!;
  const defaultV = args[args.length - 1]!;
  const pairs = args.slice(1, -1);
  let expr = defaultV;
  for (let i = pairs.length - 2; i >= 0; i -= 2) {
    expr = `(if (${discriminant} eq ${pairs[i]}) then ${pairs[i + 1]} else ${expr})`;
  }
  return expr;
}

function xqString(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function xqComment(value: string): string {
  return value.replace(/:\)/g, ": )");
}
