import { assertEquals, assert } from "@std/assert";
import { dirname, fromFileUrl, join } from "@std/path";
import { generate, generateGoTemplate } from "@intehrgrator/core/codegen/mod.ts";
import { createEmptyModel, applyExpressionEdit } from "@intehrgrator/core/mapping_model/mod.ts";
import { runTest } from "@intehrgrator/core/test_runner/mod.ts";
import { Blockly } from "@intehrgrator/blockly/blockly_core.ts";
import { initBlocklyGenerators } from "@intehrgrator/blockly/mod.ts";
import type { MappingModel } from "@intehrgrator/types/mod.ts";

const root = join(dirname(fromFileUrl(import.meta.url)), "..");

function modelWithSlots(slots: Array<{ slotId: string; expression: string; label?: string }>): MappingModel {
  let model = createEmptyModel("test-template");
  for (const s of slots) {
    model = applyExpressionEdit(model, s.slotId, s.expression, {
      rmType: "DV_TEXT",
      returnType: "string",
      label: s.label,
    });
  }
  return model;
}

Deno.test("go-template codegen from slot expressions", () => {
  const model = modelWithSlots([
    { slotId: "systolic", expression: 'xpathNumber("$.vitals.systolic")', label: "Systolic" },
    { slotId: "name", expression: 'maps_get("defaults", "PatientName")', label: "Name" },
  ]);
  const output = generate(model, "go-template");
  assert(output.includes("Generated by intEHRgrator"), "should have header");
  assert(output.includes("index .Data"), "source query → index .Data");
  assert(output.includes(".Parameters.PatientName"), "defaults → .Parameters");
});

Deno.test("go-template codegen adapter is registered", () => {
  const model = createEmptyModel("test");
  const output = generate(model, "go-template");
  assert(output.includes("Go text/template"), "should identify as Go template");
});

Deno.test("go-template codegen from Blockly state with xml_element", () => {
  const model = createEmptyModel("test");
  const blocklyState = {
    blocks: {
      blocks: [
        {
          type: "xml_element",
          fields: { TAG: "Note" },
          inputs: {
            TEXT: {
              block: {
                type: "source_query",
                fields: { EXPRESSION: "path/to/value|value" },
              },
            },
          },
        },
      ],
    },
  };
  const output = generateGoTemplate(model, { blocklyState });
  assert(output.includes("<Note>"), "should emit XML open tag");
  assert(output.includes("</Note>"), "should emit XML close tag");
  assert(output.includes('index .Data "path/to/value|value"'), "should emit index .Data for source query");
});

Deno.test("go-template codegen from Blockly state with controls_if", () => {
  const model = createEmptyModel("test");
  const blocklyState = {
    blocks: {
      blocks: [
        {
          type: "controls_if",
          extraState: { elseIfCount: 0, hasElse: false },
          inputs: {
            IF0: {
              block: {
                type: "logic_compare",
                fields: { OP: "EQ" },
                inputs: {
                  A: { block: { type: "source_query", fields: { EXPRESSION: "symptom|value" } } },
                  B: { block: { type: "text", fields: { TEXT: "Ja" } } },
                },
              },
            },
            DO0: {
              block: {
                type: "xml_element",
                fields: { TAG: "TextKeyWord" },
                inputs: {
                  TEXT: { block: { type: "text", fields: { TEXT: "Symptom present" } } },
                },
              },
            },
          },
        },
      ],
    },
  };
  const output = generateGoTemplate(model, { blocklyState });
  assert(output.includes("if eq"), "should emit if eq condition");
  assert(output.includes('(index .Data "symptom|value")'), "source query in condition");
  assert(output.includes('"Ja"'), "comparison value");
  assert(output.includes("<TextKeyWord>"), "conditional XML");
  assert(output.includes("{{- end }}"), "end block");
});

Deno.test("go-template codegen maps_get defaults → .Parameters", () => {
  const model = createEmptyModel("test");
  const blocklyState = {
    blocks: {
      blocks: [
        {
          type: "maps_get",
          fields: { NAME: "defaults" },
          inputs: {
            KEY: { block: { type: "text", fields: { TEXT: "Time" } } },
          },
        },
      ],
    },
  };
  const output = generateGoTemplate(model, { blocklyState });
  assert(output.includes(".Parameters.Time"), "defaults key → .Parameters.Time");
});

Deno.test("Handlebars Output mode executes the authored template in Conversion Test Run", () => {
  const model = createEmptyModel("test");
  const result = runTest(model, '{"name": "Ada"}', "json", {
    outputMode: "handlebars",
    handlebarsTemplate: "Hello {{name}}!",
  });
  assertEquals(result.ok, true);
  assertEquals(result.output, "Hello Ada!");
});

Deno.test("Handlebars Output mode with slot references in authored template", () => {
  let model = createEmptyModel("test");
  model = applyExpressionEdit(model, "greeting", 'xpathString("$.name")', {
    rmType: "DV_TEXT", returnType: "string", label: "Greeting",
  });
  const result = runTest(model, '{"name": "Ada"}', "json", {
    outputMode: "handlebars",
    handlebarsTemplate: 'Greeting: {{slot "greeting"}}',
  });
  assertEquals(result.ok, true);
  assert(String(result.output).includes("Ada"), "slot value should be resolved");
});

Deno.test("Go template Output mode returns error when WASM is not loaded", () => {
  const model = createEmptyModel("test");
  const result = runTest(model, '{"x": 1}', "json", {
    outputMode: "go-template",
    generatedCode: '{{ index .Data "x" }}',
  });
  assertEquals(result.ok, false);
  assert(String(result.error).includes("WASM"), "should mention WASM");
});

Deno.test("Go template Output mode with empty code returns error", () => {
  const model = createEmptyModel("test");
  const result = runTest(model, '{"x": 1}', "json", {
    outputMode: "go-template",
  });
  assertEquals(result.ok, false);
  assert(String(result.output).includes("No Go template code"), "should explain missing code");
});

Deno.test("chemo symptoms Blockly loads in headless workspace", () => {
  initBlocklyGenerators();
  const text = Deno.readTextFileSync(
    join(root, "examples/patient-reported-chemotherapy-symptoms/mapping/mapping.blockly.json"),
  );
  const state = JSON.parse(text);
  const ws = new Blockly.Workspace();
  try {
    Blockly.serialization.workspaces.load(state, ws);
    const types = new Set(ws.getAllBlocks(false).map((b) => b.type));
    assert(types.has("go_xml_element"), "should contain go_xml_element blocks");
    assert(types.has("go_xml_comment"), "should contain go_xml_comment blocks");
    assert(types.has("controls_if"), "should contain conditional blocks");
    assert(ws.getAllBlocks(false).length >= 40, "should load the full example tree");
  } finally {
    ws.dispose();
  }
});

Deno.test("chemo symptoms Blockly generates TakeCare XML Go template", () => {
  const text = Deno.readTextFileSync(
    join(root, "examples/patient-reported-chemotherapy-symptoms/mapping/mapping.blockly.json"),
  );
  const blocklyState = JSON.parse(text);
  const model = createEmptyModel("chemo-symptoms");
  const output = generateGoTemplate(model, { blocklyState });
  assert(output.includes("<ProfdocHISMessage MsgType=\"Request\">"), "root message with attribute");
  assert(output.includes(".Parameters.Time"), "header defaults from Parameters");
  assert(output.includes("<TextKeyWord>"), "symptom keyword elements");
  assert(output.includes('index .Data "patientrapporterade_symptom'), "FLAT source paths");
  assert(output.includes("2811"), "fatigue TermId");
  assert(output.includes("13700"), "document UID TermId");
  assert(output.includes("if ne"), "conditional symptom sections");
});
