// Generated by intEHRgrator — Conversion Script (TypeScript)
// Template: https://example.invalid/dummy-json-vitals/target.schema.json
// Source: Mapping Model slots (no canvas / skeleton available)
// Mapping preview Test Run evaluates Mapping Model slots through the Target
// instance format handler (ADR 0001). TypeScript Output mode executes this script.

import {
  evaluateXPathToString,
  evaluateXPathToNumber,
} from "fontoxpath";

export type SourceContext = { format: string; data: unknown };

export function convertSourceToComposition(
  sourceCtx: SourceContext,
  defaults: Record<string, unknown> = {},
) {
  function jsonQuery(path: string): string {
    const trimmed = path.trim();
    if (!trimmed || trimmed.startsWith("/")) return trimmed;
    const asJson = trimmed.startsWith("$") ? trimmed : `$.${trimmed.replace(/^\./, "")}`;
    let body = asJson.slice(1);
    if (body.startsWith(".")) body = body.slice(1);
    if (!body || body === ".") return "$source";
    const segments: string[] = [];
    let i = 0;
    while (i < body.length) {
      if (body[i] === ".") { i++; continue; }
      if (body[i] === "[") {
        const close = body.indexOf("]", i + 1);
        if (close < 0) break;
        segments.push(body.slice(i + 1, close));
        i = close + 1;
        continue;
      }
      let end = i;
      while (end < body.length && !".[".includes(body[end] ?? "")) end++;
      segments.push(body.slice(i, end));
      i = end;
    }
    return segments.reduce((q, seg) => {
      if (/^\d+$/.test(seg) || /^[A-Za-z_][A-Za-z0-9_]*$/.test(seg)) return `${q}?${seg}`;
      return `${q}?(${JSON.stringify(seg)})`;
    }, "$source");
  }

  function xpathString(path: string, node: unknown = sourceCtx.data): string {
    if (path.trim().startsWith("/")) return evaluateXPathToString(path, node);
    return evaluateXPathToString(jsonQuery(path), null, null, { source: node });
  }

  function xpathNumber(path: string, node: unknown = sourceCtx.data): number {
    if (path.trim().startsWith("/")) return evaluateXPathToNumber(path, node);
    return evaluateXPathToNumber(jsonQuery(path), null, null, { source: node });
  }

  const values: Record<string, unknown> = {};

  // systolic
  values["https://example.invalid/dummy-json-vitals/target.schema.json:$.systolic"] = xpathNumber("$.systolic");

  // diastolic
  values["https://example.invalid/dummy-json-vitals/target.schema.json:$.diastolic"] = xpathNumber("$.diastolic");

  // unit
  values["https://example.invalid/dummy-json-vitals/target.schema.json:$.unit"] = xpathString("$.unit");

  return values;
}
