/** English web app chrome. Other locales must provide the same keys. */
export const en = {
  appTitle: "intEHRgrator — Integration Workbench",
  copyPrompt: "Copy prompt",
  copyPromptTitle: "Copy AI prompt with files embedded",
  callAi: "Call AI",
  callAiTitle: "Call the configured AI with mapping tools (MCP / Agent API names)",
  aiMenuAria: "AI prompt delivery options",
  menuCopyPrompt: "Copy prompt",
  menuCallAi: "Call AI",
  menuAiCredentials: "AI credentials…",
  menuEmbedFiles: "Embed files in prompt",
  menuAttachFiles: "Attach files in chat",
  menuBrowseUris: "Browse URIs (when available)",
  importAi: "Import AI suggestions",
  exampleSets: "Example Sets",
  exampleSetsTitle: "Load a complete example set (source, target, optional mapping) from catalog URIs",
  exampleSetsMenuAria: "Choose example set",
  functions: "Functions",
  functionsTitle: "Save, load, or contribute Blockly Functions; browse the GitHub Function library",
  newProject: "New Project",
  loadProject: "Load Project",
  saveAs: "Save as",
  exportProject: "Export Project",
  importProject: "Import Project",
  betterForm: "Open Better form",
  betterFormTitle: "Requires licensed Better renderer (deno task setup:better-forms)",
  help: "Help",
  helpTitle: "Tutorial and issue reporting",
  helpMenuAria: "Help menu",
  userTutorial: "User tutorial",
  reportBug: "Report a bug",
  requestFeature: "Request a feature",
  uiLanguageAria: "Application UI language",
  showSource: "Source",
  source: "Source",
  clickToMapAria: "Click-to-Map into Handlebars",
  clickToMapHtml:
    "Click a Source Schema or Example Instance node to map it into the selected Blockly block. If a Code text block (LANG = Handlebars) or a Handlebars text block is selected, the click inserts a VMS-Hbs {{path}} at the caret. Hold Shift for nested {{#with}} / {{#each}}. Otherwise Listening Mode fills the waiting Source query block.",
  slideSourceAway: "Slide Source away",
  handlebarsHint: "Handlebars insert ready — click a source node for {{path}}; Shift+click for nested #with/#each.",
  schema: "Schema",
  schemaFormatsAria: "Supported schema formats",
  schemaFormatsHtml:
    "Supported: JSON Schema, JSON or XML documents, XSD samples, and openEHR Web Template, Composition JSON, or a GitHub .t.json (archetypes fetched from the same repo).<br>Load from a local file, a URL, or ▾ → From GitHub template….",
  loadSchema: "Load Schema",
  schemaMenuAria: "More schema load options",
  examples: "Examples",
  exampleFormatsAria: "Supported example formats",
  exampleFormatsHtml:
    "Supported: JSON or XML instance files.<br>Load one file, a local folder, a GitHub folder (▾), or a single file from URL.",
  addExample: "+ Add Example",
  exampleMenuAria: "More example load options",
  mappingEditors: "Mapping Editors",
  undo: "Undo",
  redo: "Redo",
  expandAll: "Expand all",
  expandAllTitle: "Expand all nested blocks",
  collapseAll: "Collapse all",
  collapseAllTitle: "Collapse all nested blocks",
  followAgent: "Follow agent",
  followAgentTitle: "When enabled, pan the main canvas to blocks an agent just edited",
  openViewer: "Open viewer window",
  openViewerTitle: "Open viewer window: live canvas, agent legend, and attributed history timeline",
  downloadJson: "Download JSON",
  downloadWorkspaceTitle: "Download full Blockly workspace JSON (includes block coordinates and layout)",
  mappingViewsAria: "Mapping editor text views",
  mappingSpec: "Mapping Spec",
  specLayoutAria: "Mapping Spec view options",
  listView: "List view (all roots)",
  tabbedView: "Tabbed view (per root)",
  download: "Download",
  downloadSpecTitle: "Download the full Blockly workspace JSON",
  upload: "Upload",
  uploadSpecTitle: "Upload a Blockly workspace JSON file",
  markWarned: "Mark warned optional",
  markWarnedTitle: "Mark unmapped optional scaffold trees that show a constraint warning",
  deleteMarked: "Delete marked",
  deleteMarkedTitle: "Delete checked nodes and their children from the canvas",
  undoHistoryHint: "Tip: Open canvas (observer) for the full agent timeline and attributed history.",
  undoLastEdit: "Undo last canvas edit.",
  redoLastEdit: "Redo canvas edit.",
  railTarget: "Target schema",
  railTargetTitle: "Target schema",
  railScripts: "Scripts",
  railScriptsTitle: "Generated conversion script(s)",
  railTest: "Test",
  railTestTitle: "Conversion Test Run(s)",
  targetPreviews: "Target & Previews",
  targetFormatsAria: "Supported target formats",
  targetFormatsHtml:
    "Supported: openEHR OPT/OPT2, Web Template, JSON Schema, XML Schema (XSD), ADL, free-form templates, or a GitHub .t.json (archetypes fetched from the same repo).<br>Choose a target and a default context map together. ▾ also offers file, URL, GitHub, and non-destructive refresh.",
  loadTarget: "Load target & default context map",
  loadTargetTitle: "Load a target and pick a default context map",
  targetMenuAria: "More target load options",
  modelLanguageAria: "Target model ontology language",
  scriptFormatsAria: "Conversion script formats",
  scriptFormatsHtml:
    "Mapping preview interprets the mapping without generating a script. Conversion scripts (so far): TypeScript, Java, Handlebars, XQuery, and Go Template. TypeScript, Handlebars, Go Template, and XQuery also run in Conversion Test Run. Java generates an Archie class but does not execute in the web app. For openEHR targets, JSON vs XML instance chooses how XQuery serializes the composition.<br>Download on the script editor saves the generated script. The overlay Download on Conversion Test Run saves that instance.",
  mappingPreview: "Mapping preview",
  instance: "Instance",
  instanceTitle: "Desired openEHR instance shape. XQuery export and Test Run use this serialization.",
  jsonInstance: "JSON instance",
  xmlInstance: "XML instance",
  slideTargetAway: "Slide Target & Previews away",
  tabTargetSchema: "Target schema",
  tabScripts: "Generated conversion script(s)",
  tabTest: "Conversion Test Run(s)",
  generatedScripts: "Generated conversion script(s)",
  downloadScriptTitle: "Download conversion script",
  testRuns: "Conversion Test Run(s)",
  validateAs: "Validate as",
  validateTitle: "ehrtslib JSON deserializer preset for template validation",
  hybrid: "Hybrid (lenient)",
  defaultMode: "Default",
  compact: "Compact",
  canonicalStrict: "Canonical strict",
  terse: "Terse",
  runTest: "Run Test",
  autoplay: "▶ Autoplay",
  pause: "⏸ Pause",
  downloadTestTitle: "Download Conversion Test Run output",
  ready: "Ready",
  loadSchemaEmpty: "Load a schema file.",
  selectExampleTab: "Select an example tab.",
  addExamplesEmpty: 'Add example instance(s) to enable "Conversion Test Run(s)" in Target & Previews',
  loadTargetEmpty: "Load a target schema or template.",
  statusNoTarget: "No target",
  statusTarget: "Target: {id}",
  statusScript: "Script: {name}",
  statusNoExample: "No example",
  statusExample: "Example: {name}",
  statusUnmapped: "{n} unmapped mandatory",
  unsavedChanges: "unsaved changes",
  autosavedAt: "autosaved at {time}",
  functionsIntroHtml:
    "Save a Blockly Function (definition + Decision tables) to disk, load one into this mapping, or browse the GitHub Function library. Contribute files a review issue — it does not auto-merge.",
  onThisCanvas: "On this canvas",
  loadFromDisk: "Load from disk…",
  functionLibrary: "Function library",
  catalogUrl: "Catalog URL",
  loadCatalog: "Load catalog",
  close: "Close",
  nameInUse: "Name already in use",
  cancel: "Cancel",
  replace: "Replace",
  rename: "Rename",
  contributeTitle: "Contribute Function",
  contributeIntroHtml:
    "Opens a GitHub issue on <code>regionstockholm/intehrgrator</code> with your description and the Function definition. Maintainers review by hand.",
  functionName: "Function:",
  descriptionRequired: "Description (required)",
  contributePlaceholder: "What it returns, locale, Decision table, parameters…",
  needGithubHtml:
    'Need a GitHub account? <a id="function-contribute-signup" href="https://github.com/signup" target="_blank" rel="noopener noreferrer">Create an account</a> or <a id="function-contribute-login" href="https://github.com/login" target="_blank" rel="noopener noreferrer">log in</a>, then submit.',
  openGithubIssue: "Open GitHub issue",
  saveAsIntro: "Save the current workspace under a name you can load later.",
  projectName: "Project name",
  projectNamePlaceholder: "My integration project",
  save: "Save",
  loadProjectTitle: "Load project",
  loadProjectIntro: "Select a saved workspace. Loading replaces the current project.",
  loadFromUrl: "Load from URL",
  loadUrlHint: "Paste an https URL. GitHub file pages are converted to raw content.",
  urlLabel: "URL",
  recentUrls: "Recent URLs",
  load: "Load",
  jointTitle: "Load target & default context map",
  jointIntroHtml:
    "Pick a target and a default context map together. Confirm scaffolds the <strong>Template Skeleton</strong> and <strong>Default point</strong>s. <strong>New</strong> loads the target into the Target schema tab only so you can pull chips and values, then Apply on the canvas block.",
  targetLegend: "Target",
  noTargetYet: "No target selected yet.",
  fromFile: "From file…",
  useLoadedTarget: "Use loaded target",
  targetUrl: "Target URL",
  fetchUrl: "Fetch URL",
  mapLegend: "Default context map",
  factoryMapHtml: "openEHR factory (<code>defaults_openEHR_1</code>)",
  keepMap: "Keep the map already on the canvas",
  newMap: "New (empty) — Target schema first, then Apply",
  browsedFile: "Browsed file",
  browseMap: "Browse map file…",
  loadAndScaffold: "Load & scaffold",
  loadIntoSchema: "Load into Target schema",
  refreshReport: "Refresh report",
  copyMergePrompt: "Copy merge prompt",
  aiCredentialsTitle: "AI credentials",
  aiCredentialsIntroHtml:
    'Optional OpenAI-compatible chat endpoint so <strong>Call AI</strong> can map from the web app. Credentials stay in this browser only — not in the Project Bundle. <strong>Call AI</strong> can use the same mapping tools as MCP / the HTTP Agent API (<code>map_slot</code>, <code>import_suggestions</code>, <code>run_test</code>, …). An AI-assisted IDE with local MCP remains a separate, fully valid path. Step-by-step key pages: <a href="https://github.com/regionstockholm/intehrgrator/blob/main/docs/AI_CREDENTIALS.md" target="_blank" rel="noopener noreferrer" id="ai-credentials-guide">Call AI credentials</a>.',
  provider: "Provider",
  customEndpoint: "Custom OpenAI-compatible endpoint",
  getApiKey: "Get an API key",
  providerDocs: "Provider docs",
  endpoint: "Endpoint",
  apiKey: "API key",
  model: "Model",
  howCallAiMaps: "How Call AI maps",
  mappingTools: "Mapping tools (MCP / Agent API names on the live workbench)",
  suggestionsOnly: "Suggestions JSON only (one-shot import)",
  clear: "Clear",
  defaultsTitle: "Default context map",
  defaultsIntro: "Load a saved map, browse a file or URL, download the unique default context map, or save the current canvas map under a name.",
  browseFile: "Browse file…",
  loadUrlBtn: "Load URL",
  downloadFile: "Download file…",
  saveAsEllipsis: "Save as…",
  saveDefaultsTitle: "Save default context mapping as",
  saveDefaultsIntro: "Store the current default context mapping under a name you can pick later.",
  nameLabel: "Name",
  hardcodeTitle: "Hardcode default context mapping entry",
  hardcodeIntroHtml:
    "Choose a map key to <strong>inline</strong> on the canvas. Every <code>get defaults key …</code> lookup for that key is replaced with a copy of the value from this default context mapping. After that, those slots no longer read the convert-time <code>defaults</code> argument — they use the hardcoded block instead. The default context mapping itself is left unchanged so you can hardcode other keys later or keep the entry for remaining lookups.",
  importAiTitle: "Import AI suggestions",
  importAiIntroHtml:
    "Paste the JSON from the AI chat (a raw object or an <code>intehrgrator-suggestions</code> fence). Import validates against the suggestion JSON Schema; errors stay visible here and can be copied back to the AI.",
  suggestions: "Suggestions",
  pasteClipboard: "Paste clipboard",
  copyErrorsForAi: "Copy errors for AI",
  copied: "Copied",
  importAction: "Import",
  notRecommended: "Not on the recommended version",
  bleedingEdgeHtml:
    'Prefer to experiment? The bleeding-edge build (updated on every change to <code>main</code>) is always at <a id="recommended-version-bleeding-edge-link" href="#">the site root</a>.',
  newHereHtml:
    'New here? Read the <a id="recommended-version-tutorial-link" href="#">tutorial</a> or the <a id="recommended-version-readme-link" href="#">README</a>.',
  dontShowAgain: "Don't show this again for this version",
  dismiss: "Dismiss",
  defaultsBlockAria: "About the default context map",
  defaultsBlockHtml:
    "<strong>Default context map</strong> is the unique canvas table you author here. At <em>convert time</em>, generated Conversion Scripts receive it as a <code>defaults</code> argument keyed by <strong>runtime key</strong> (<code>language</code>, <code>facility</code>, …). <code>maps_get(\"defaults\", runtimeKey)</code> looks those up. Runtime code can merge that bag with per-message values, other named maps, and Sheet grids — the canvas map is the reusable baseline, not literals baked into every slot.<br><strong>Scaffold targets</strong> (chips) are authoring-only RM paths, not convert-time keys: <code>Class.attribute</code> (e.g. <code>COMPOSITION.composer</code>, <code>EVENT_CONTEXT.health_care_facility</code>), ancestor paths, and wildcards (<code>*.language</code> lights every language slot). A more specific chip wins when several match the same slot. Empty chips → a runtime-only key that lights nothing. Extra keys stay available for Map lookups even if they do not light a slot.<br>Confirm, <strong>Apply default context map</strong>, or a later target refresh join <strong>Default point</strong>s. Value edits are live in Test Run. A slot already mapped from source is not replaced.<br>The folder opens load/save: pick a map saved in this browser, browse a JSON file, load a URL, save a named copy, or download the current map as JSON you can upload again later.",
  decisionBlockAria: "About decision tables",
  decisionBlockHtml:
    "<strong>Decision table</strong> is a named rule grid in the Tables &amp; Sheets tab: condition columns (equality, don't-care <code>—</code>) and output columns (plain values or VMS-Mustache snippets). The grid owns column names and types; this block’s locals Map keys stay in sync.<br>Plug a Map of locals on the right (keys = condition headers). The output dropdown returns one typed column (🔤 string, 🔢 number, ✓ boolean), or <em>all outputs</em> as a Map (↦). Switching that type may unplug the block; canvas undo/redo restores it.<br>Hit policy (FIRST / UNIQUE / COLLECT) is on the Tables &amp; Sheets tab. Flatten nested sources into the locals Map (or via variables) before eval.",
  fromUrl: "From URL…",
  refreshFromFile: "Refresh from file…",
  refreshFromUrl: "Refresh from URL…",
  noRecentUrls: "No recent URLs yet.",
  removeFromHistory: "Remove {url} from history",
  enterUrl: "Enter a URL.",
  refreshKindFromUrl: "Refresh {kind} from URL",
  refreshUrlHint: "Reload this file from a URL without wiping canvas mappings. Warnings list slots or paths that may no longer fit.",
  kindSchema: "schema",
  kindExample: "example",
  kindTarget: "target",
  kindSource: "source",
  fromLocalFolder: "From local folder…",
  fromGithubFolder: "From GitHub folder…",
  fromGithubTemplate: "From GitHub template…",
  loadSchemaFromUrl: "Load schema from URL",
  loadSchemaUrlHint: "JSON, XML, XSD, or a GitHub .t.json template (archetypes are fetched from the same repo). GitHub file pages are converted to raw content.",
  recentSchemaUrls: "Recent schema URLs",
  githubTemplateTitle: "Load openEHR template from GitHub",
  githubTemplateHint: "Paste a GitHub blob or raw URL to a Better .t.json (or .adl / .opt). Dependent archetypes are pulled from the same repository branch.",
  githubTemplateOpenTitle: "Open openEHR template from GitHub",
  addExampleFromUrl: "Add example from URL",
  addExampleUrlHint: "JSON or XML instance. GitHub file pages are converted to raw content.",
  recentExampleUrls: "Recent example URLs",
  githubFolderTitle: "Add examples from GitHub folder",
  githubFolderHint: "Paste a GitHub tree URL to a folder. All JSON and XML files under that path are loaded.",
  loadTargetFromUrl: "Load target from URL",
  loadTargetUrlHint: "OPT, Web Template, JSON Schema, or a GitHub .t.json. GitHub file pages are converted to raw content.",
  recentTargetUrls: "Recent target URLs",
  loadingCatalog: "Loading catalog…",
  exampleSetsHeading: "Example sets",
  noExampleSets: "No example sets in catalog",
  catalog: "Catalog",
  bundledCatalog: "Bundled dummy catalog",
  ehrtslibCatalog: "ehrtslib catalog (GitHub)…",
  loadCatalogFromUrl: "Load catalog from URL…",
  catalogUrlPrompt: "Example-set catalog JSON URL",
  confirmLoadExampleSet: "Load this example set? The current workspace will be replaced. Unsaved changes may be lost.",
  confirmNewProject: "Start a new project? The current workspace will be cleared. Unsaved changes may be lost.",
  confirmNewEmpty: "Start a new empty project?",
  confirmLoadProject: "Load this project? The current workspace will be replaced.",
  noSavedProjects: "No saved projects yet. Use Save as or wait for autosave.",
  lastAutosave: "Last autosave",
  savedProject: "Saved project",
  defaultsUnavailable: "Defaults catalog unavailable: {detail}",
  noSavedMaps: "No saved default context mappings yet. Use Save as, Download, Browse file, or a URL.",
  savedMap: "Saved map",
  noHardcodeEntries: "The default context mapping has no entries to hardcode yet.",
  selectedFile: "Selected: {name}",
  usingLoaded: "Using loaded: {name}",
  fetchedFile: "Fetched: {name}",
  browsedFileLabel: "Browsed file: {name}",
  pasteTargetUrl: "Paste a target URL first.",
  popupBlockedSvg: "Popup blocked — downloaded SVG instead.",
  popupBlockedEmpty: "Popup blocked and the canvas is empty.",
  openedObserver: "Opened agent observer / canvas snapshot.",
  betterMissing: "Better Form Renderer not installed. Run: deno task setup:better-forms",
  schemaMismatch: "Schema mismatch:",
  conversionFailed: "Conversion failed:",
  templateValidation: "Template validation:",
  noWorkspace: "No Blockly workspace",
  noFunctionsOnCanvas: "No Functions on the canvas. Extract to function, or load from the library.",
  contribute: "Contribute",
  loadCatalogBrowse: "Load the catalog to browse curated Functions.",
  catalogNoFunctions: "Catalog has no Functions.",
  loadingLibrary: "Loading Function library…",
  fnReturnsValue: "{sig} → value",
  pasteJsonFirst: "Paste the AI JSON (or an intehrgrator-suggestions fence) first",
  clipboardEmpty: "Clipboard is empty or not readable in this browser",
  noMatches: "No matches",
  searchPlaceholder: "Search…",
  filterList: "Filter list",
  historyTimeline: "History timeline",
  historyIntro: "Scrub to preview; rollback truncates later entries. Patch undo returns intehrgrator-suggestions v2 JSON.",
  seqLabel: "Seq",
  previewAtSeq: "Preview at seq",
  rollbackHere: "Rollback here (destructive)",
  copyPatchUndo: "Copy patch-undo prompt",
  timelineDesktopOnly: "Agent API timeline is only available in the desktop app.",
  timelineUnavailable: "Agent API unavailable — timeline idle.",
  noHistoryYet: "No history yet.",
  selectHistoryPoint: "Select a history point.",
  downloadDiscardedConfirm: "Download the discarded branch (.intehrgrator) before continuing?",
  noBundleExport: "No bundle data to export for discarded branch.",
  downloadedDiscarded: "Downloaded discarded branch.",
  agentsHeading: "Agents",
  projectLoaded: "Project loaded",
  newProjectStatus: "New project",
  projectNotFound: "Project not found",
  projectImported: "Project imported",
  restoredMapping: "Restored previous mapping",
  blocklyMustBeObject: "Blockly JSON must be an object",
  exampleDropJsonXml: "Example drop: JSON or XML files only",
  listeningSourceQuery: "Listening for source path → source query",
  appliedDefaults: "Applied default context map",
  refreshPromptCopied: "Refresh merge prompt copied",
  callingAi: "Calling AI…",
  providerRejectedTools: "Provider rejected mapping tools; retrying suggestions JSON…",
  aiCredentialsCleared: "AI credentials cleared",
  aiCredentialsSaved: "AI credentials saved in this browser",
  saveAiOrCopy: "Save AI credentials to Call AI, or use Copy prompt.",
  loadTargetFirst: "Load a target into Target schema first, then Apply default context map.",
  targetNodeMissing: "That Target schema node is not in the loaded target.",
  dropLeafHint: "Drop a leaf onto scaffold-target chips, a subtree onto a value socket, or onto empty canvas.",
  emptyMapReady: "Empty default context map ready — pull from Target schema, then Apply.",
  pickTargetFirst: "Pick a target file or URL first.",
  corsCallAiHint: "Browser CORS often blocks cloud providers from GitHub Pages. Use the desktop app (it forwards Call AI), enable CORS on a local server (Ollama / LM Studio), or use Copy prompt.",
  savedAs: 'Saved as "{name}"',
  loadedSchema: "Loaded schema {name}",
  loadedBlockly: "Loaded Blockly mapping {name}",
  loadedTargetIntoSchema: "Loaded {format} target {id} into Target schema (no product scaffold yet)",
  loadedTarget: "Loaded {format} target {id}",
  loadedFunctionLibrary: "Loaded Function library ({n})",
  loadedFunction: "Loaded Function {name}",
  loadedExampleCatalog: "Loaded example-set catalog ({n} {sets})",
  setSingular: "set",
  setPlural: "sets",
  loadedExampleSet: 'Loaded example set "{name}"',
  exampleSetFailed: 'Example set "{name}" failed: {detail}',
  addedExample: "Added example {name}",
  addedExampleMismatch: "Added example {name} with {n} schema {mismatch}",
  mismatchSingular: "mismatch",
  mismatchPlural: "mismatches",
  addedExamples: "Added {n} examples",
  addedExamplesMismatch: "Added {n} examples with {m} schema {mismatch}",
  aiPromptCopied: "AI prompt copied ({delivery})",
  listeningSlot: "Listening for source path → {slot}",
  mappedWhat: "Mapped {what}",
  mappedSourceQuery: "Mapped source query {xpath}",
  importSummary: "Import: {applied} applied, {loops} loops, {skipped} skipped, {errors} errors{schema}",
  importSchemaNote: ", {n} schema",
  importFailed: "Import failed: {detail}",
  targetLoadFailed: "Target load failed: {detail}",
  exampleLoadFailed: "Example load failed: {detail}",
  exampleFolderFailed: "Example folder load failed: {detail}",
  functionCatalogFailed: "Function library catalog failed: {detail}",
  exampleCatalogFailed: "Example-set catalog failed: {detail}",
  blocklyParseFailed: "Blockly JSON parse failed: {detail}",
  couldNotLoad: "Could not load {name}: {detail}",
  autosaveFailed: "Autosave failed: {detail}",
  modelLanguageStatus: "Model language: {language}",
  refreshedClean: "Refreshed {kind} {name} with no mapping conflicts.",
  refreshedWithWarnings: "Refreshed {kind} {previous} → {next}",
  warningCount: "{n} {warnings}:",
  warningSingular: "warning",
  warningPlural: "warnings",
  loadedGithubTemplate: "Loaded GitHub template {id} ({n} files){extra}",
  loadedGithubSchema: "Loaded GitHub schema {id} ({n} files){extra}",
  warningsParen: " ({n} warnings)",
  callAiFailed: "Call AI failed: {detail}",
  scaffoldTarget: "Scaffold target {path} (click the chip to toggle *.)",
  nestedOnMap: "Nested {label} on the default context map",
  addedMapEntry: "Added entry {key} ({path}) at row {row}",
  addedFromTarget: "Added {label} from Target schema",
  addedSource: "Added source {xpath}",
  taskLoadGithub: "Load GitHub clinical model",
  taskLoadAndScaffold: "Load and scaffold target",
  taskLoadExampleSet: "Load example set",
  taskLoadTarget: "Load target",
  taskLoadSchema: "Load source schema",
  taskLoadMapping: "Load mapping",
  taskLoadSheets: "Load sheets",
  taskLoadDefaults: "Load defaults map",
  taskParseUrl: "Parse GitHub URL",
  taskIndexTree: "List repository files",
  taskFetchFiles: "Fetch clinical model files",
  taskParseModels: "Parse templates and archetypes",
  taskResolveOpt: "Resolve operational template",
  taskScaffold: "Scaffold Template Skeleton",
  taskGenerate: "Generate conversion script",
  taskLoadExampleN: "Load example {n}",
  appDescription: "intEHRgrator — visual integration workbench for mapping source data to openEHR",
  loadedColon: "Loaded: {name}",
  savedColon: "Saved: {name}",
  noMappingConflicts: "No mapping conflicts.",
  refreshReportLine: "{kind} {previous} → {next}",
  refreshWarningCount: "{n} warning(s):",
  hardcodedLookups: "Hardcoded “{key}” into {n} {lookups}",
  lookupSingular: "lookup",
  lookupPlural: "lookups",
  noDefaultsLookups: "No maps_get(\"defaults\", \"{key}\") lookups found on the canvas",
  callAiResult: "Call AI: {applied} applied · {errors} errors{extra}",
  functionLibraryCount: "Function library: {n} {functions}",
  functionSingular: "Function",
  functionPlural: "Functions",
  renamedFromParen: " (renamed from {name})",
  savedBundle: "Saved {name}",
  descriptionForFunction: "Description for Function \"{name}\" (optional):",
  clashExist: "{bits} already exist. Rename keeps both (default). Replace overwrites the existing definition.",
  functionQuoted: "Function \"{name}\"",
  decisionQuoted: "Decision table \"{name}\"",
  andWord: "and",
  openedContributionIssue: "Opened contribution issue for {name}",
  openedGithubForm: "Opened GitHub new-issue form for {name}",
  entrySummary: "{description} Parameters: {params}. Decision tables: {tables}.",
  recommendedFrozen: "You are using intEHRgrator {current}, which is not the recommended end-user version ({recommended}).",
  recommendedBleeding: "You are using the bleeding-edge build (updated on every change to main), not the recommended stable version ({recommended}).",
  goToRecommended: "Go to recommended version ({tag})",
  previewingSeq: "Previewing seq {n}…",
  previewLoadedSeq: "Preview loaded for seq {n} (read-only; main canvas unchanged).",
  rollbackAsk: "Rollback to seq {seq}?\n\n{n} later entries will be discarded.\n\nDownload the discarded branch (.intehrgrator) before continuing?",
  confirmRollback: "Confirm destructive rollback to seq {seq}?",
  rolledBackSeq: "Rolled back to seq {n}. Main canvas will sync.",
  patchPromptCopied: "Patch prompt copied (intehrgrator-suggestions v2). Apply via import_suggestions.",
  noAgentsYet: "No agents connected yet.",
  optionalAttributes: "Optional attributes…",
  openViewerMenu: "Open viewer window…",
} as const;

export type ChromeMessages = { [K in keyof typeof en]: string };
