/**
 * Blockly workspace → Go text/template conversion script.
 *
 * Preferred over the JSON walker when a canvas snapshot is available so
 * loops, Optional RM Insertion, and live block edits show up in Generated
 * conversion script(s).
 */

import type { Block, Workspace } from "blockly/core";
import { Blockly } from "./blockly_core.ts";
import { blockToExpression } from "./expression_serialize.ts";
import {
  isDataValueBlock,
  isRmContainerBlockType,
  rmAttributeInputName,
  RM_ATTR_INPUT_PREFIX,
  RM_SPECIALIZATION_INPUT,
} from "./blocks/rm_blocks.ts";
import { isGenericValueBlockType, isSchemaStructureBlock, targetChildInputName } from "./blocks/target_blocks.ts";
import { xmlDeclarationOf, xmlNamespacesOf } from "./blocks/xml_blocks.ts";
import { registerSchemaBlocksFromSkeleton } from "./schema_blocks.ts";
import { DEFAULTS_BLOCK_TYPE } from "../core/defaults/extract.ts";
import {
  CONVERSION_START_TYPE,
  findInstanceRootUnderStart,
  TEXT_DOCUMENT_BLOCK_TYPE,
} from "./instance_root.ts";
import { attributesFor, isPrimitiveRmType } from "../core/rm_meta.ts";
import type { MappingModel } from "../types/mod.ts";
import {
  createGoEmitContext,
  emitGoExpressionTemplate,
  emitGoExpr,
  goQuote,
  type GoEmitContext,
} from "../core/codegen/go_template.ts";
import { parseExpression } from "../core/expression/mod.ts";
import { registerExportTargetAdapter } from "../core/codegen/mod.ts";
import { generateGoTemplate } from "../core/codegen/go_template.ts";
import { runWithoutBlocklyEvents } from "./blockly_events.ts";

const STATEMENT_INPUT_TYPE = 3;

export function registerGoTemplateExportAdapter(): void {
  registerExportTargetAdapter({
    id: "go-template",
    extension: "tmpl",
    mime: "text/x-go-template",
    generate(model, options) {
      if (options?.blocklyState) {
        const fromCanvas = generateGoTemplateFromBlocklyState(
          options.blocklyState,
          model,
          options.skeleton,
        );
        if (fromCanvas) return fromCanvas;
      }
      return generateGoTemplate(model, options);
    },
  });
}

export function generateGoTemplateFromBlocklyState(
  state: unknown,
  model: MappingModel,
  skeleton?: import("../types/mod.ts").SkeletonNode[],
): string | null {
  if (!state || typeof state !== "object") return null;
  const workspace = new Blockly.Workspace();
  try {
    const snapshot = JSON.parse(JSON.stringify(state)) as Record<string, unknown>;
    let generated: string | null = null;
    runWithoutBlocklyEvents(() => {
      if (skeleton?.length) registerSchemaBlocksFromSkeleton(skeleton);
      Blockly.serialization.workspaces.load(snapshot, workspace);
      generated = generateGoTemplateFromWorkspace(workspace, model);
    });
    return generated;
  } catch (err) {
    console.warn("Go template codegen from Blockly failed; falling back to JSON walker", err);
    return null;
  } finally {
    workspace.dispose();
  }
}

export function generateGoTemplateFromWorkspace(
  workspace: Workspace,
  model: MappingModel,
): string | null {
  const ctx = createGoEmitContext();
  const instanceRoot = findInstanceRootUnderStart(workspace);
  const roots = workspace.getTopBlocks(true).filter((block) =>
    block.type !== DEFAULTS_BLOCK_TYPE &&
    block.type !== "maps_create_with" &&
    block.type !== CONVERSION_START_TYPE
  );

  const lines: string[] = [
    `{{- /* Generated by intEHRgrator — Go text/template Conversion Script */ -}}`,
    `{{- /* Target: ${model.templateId || "free-form"} */ -}}`,
  ];

  let body: string[] | null = null;
  if (instanceRoot?.type === TEXT_DOCUMENT_BLOCK_TYPE) {
    const value = instanceRoot.getInputTargetBlock("VALUE");
    body = value ? emitBlock(value, ctx, 0) : ['""'];
  } else if (instanceRoot && (
    isSchemaStructureBlock(instanceRoot) ||
    instanceRoot.type === "json_object" ||
    instanceRoot.type === "xml_element"
  )) {
    body = emitGeneric(instanceRoot, ctx, 0);
  } else if (instanceRoot?.type === "composition" || isRmContainerBlockType(instanceRoot?.type ?? "")) {
    body = emitRmAsJson(instanceRoot, ctx, 0);
  } else {
    const generic = instanceRoot ?? roots.find((block) =>
      isSchemaStructureBlock(block) || block.type === "json_object" || block.type === "xml_element"
    );
    if (generic) {
      body = emitGeneric(generic, ctx, 0);
    } else if (roots.length) {
      body = [];
      for (const root of roots) {
        body.push(...emitBlock(root, ctx, 0));
      }
    }
  }

  if (!body?.length) return null;
  lines.push(...body);
  return lines.join("\n");
}

function emitBlock(block: Block, ctx: GoEmitContext, indent: number): string[] {
  const fromExpr = emitExpressionBlock(block, ctx);
  if (fromExpr !== null) return fromExpr;

  if (block.type === "for_each_source") return emitForEachSource(block, ctx);
  if (block.type === "for_each_list") return emitForEachList(block, ctx);
  if (block.type === "controls_if") return emitControlsIf(block, ctx);
  if (block.type === "variables_set") return [];
  if (block.type === "defaults_block" || block.type === "maps_create_with") return [];

  if (block.type === "xml_text") {
    const value = block.getInputTargetBlock("VALUE");
    return value ? emitExpressionBlock(value, ctx) ?? emitBlock(value, ctx, indent) : [];
  }
  if (block.type === "xml_cdata") {
    const value = block.getInputTargetBlock("VALUE");
    const inner = value ? (emitExpressionBlock(value, ctx) ?? emitBlock(value, ctx, indent)).join("") : "";
    return [`<![CDATA[${inner}]]>`];
  }
  if (block.type === "xml_document") {
    return emitXmlDocument(block, ctx);
  }
  if (block.type === "text_document") {
    const value = block.getInputTargetBlock("VALUE");
    return value ? emitBlock(value, ctx, indent) : [];
  }
  if (block.type === "text" || block.type === "text_code") {
    return [String(block.getFieldValue("TEXT") ?? "")];
  }
  if (block.type === "text_handlebars") {
    const script = block.getInputTargetBlock("SCRIPT");
    return script ? (emitExpressionBlock(script, ctx) ?? []) : [];
  }

  if (block.type === "element" || isRmContainerBlockType(block.type)) {
    return emitRmAsJson(block, ctx, indent);
  }
  if (isDataValueBlock(block)) {
    return emitDvAsJson(block, ctx, indent);
  }
  if (isGenericValueBlockType(block.type) || isSchemaStructureBlock(block)) {
    return emitGeneric(block, ctx, indent);
  }
  if (block.type === "xml_element" || block.type.startsWith("schema_")) {
    return emitXmlOrSchema(block, ctx);
  }
  if (block.type === "json_object" || block.type === "json_array") {
    return emitJson(block, ctx, indent);
  }

  return [`{{- /* unsupported block: ${block.type} */ -}}`];
}

function emitExpressionBlock(block: Block, ctx: GoEmitContext): string[] | null {
  const serialized = blockToExpression(block);
  if (!serialized) return null;
  return [emitGoExpressionTemplate(parseExpression(serialized), ctx)];
}

function emitForEachSource(block: Block, ctx: GoEmitContext): string[] {
  const path = String(block.getFieldValue("PATH") || "");
  const varName = String(block.getFieldValue("VAR") || "item");
  const rangeExpr = loopRangeExpr(path);
  const body = block.getInputTargetBlock("DO");
  const lines = [`{{- range ${rangeExpr} }}`];
  const innerCtx = createGoEmitContext(varName);
  if (body) lines.push(...emitBlock(body, innerCtx, 0));
  lines.push(`{{- end }}`);
  return lines;
}

function emitForEachList(block: Block, ctx: GoEmitContext): string[] {
  const varName = String(block.getFieldValue("VAR") || "item");
  const list = block.getInputTargetBlock("LIST");
  const listParts = list ? emitExpressionBlock(list, ctx) ?? emitBlock(list, ctx, 0) : ['""'];
  const listExpr = listParts.join("").replace(/^\{\{\s*/, "").replace(/\s*\}\}$/, "");
  const body = block.getInputTargetBlock("DO");
  const lines = [`{{- range ${listExpr || `index .Data ""`} }}`];
  const innerCtx = createGoEmitContext(varName);
  if (body) lines.push(...emitBlock(body, innerCtx, 0));
  lines.push(`{{- end }}`);
  return lines;
}

function loopRangeExpr(path: string): string {
  const trimmed = path.trim();
  if (trimmed.startsWith("$.")) {
    const body = trimmed.replace(/^\$\.?/, "").replace(/\[(\d+|\*)\]/g, ".$1");
    const segments = body.split(".").filter(Boolean);
    if (!segments.length) return `index .Data ""`;
    let expr = ".Data";
    for (const seg of segments) {
      expr = `index ${expr} ${goQuote(seg)}`;
    }
    return expr;
  }
  return `index .Data ${goQuote(trimmed)}`;
}

function emitControlsIf(block: Block, ctx: GoEmitContext): string[] {
  const lines: string[] = [];
  const extra = (block as Block & { extraState_?: { elseIfCount?: number; hasElse?: boolean } }).extraState_;
  const ifCount = (extra?.elseIfCount ?? 0) + 1;
  const hasElse = extra?.hasElse ?? false;

  for (let i = 0; i < ifCount; i++) {
    const cond = block.getInputTargetBlock(`IF${i}`);
    const body = block.getInputTargetBlock(`DO${i}`);
    const keyword = i === 0 ? "if" : "else if";
    const condStr = cond ? emitCondition(cond, ctx) : "true";
    lines.push(`{{- ${keyword} ${condStr} }}`);
    if (body) lines.push(...emitStatementChain(body, ctx, 0));
  }

  if (hasElse) {
    const elseBody = block.getInputTargetBlock("ELSE");
    lines.push(`{{- else }}`);
    if (elseBody) lines.push(...emitStatementChain(elseBody, ctx, 0));
  }

  lines.push(`{{- end }}`);
  return lines;
}

function emitCondition(block: Block, ctx: GoEmitContext): string {
  const serialized = blockToExpression(block);
  if (serialized) return emitGoExpr(parseExpression(serialized), ctx);
  return "true";
}

function emitStatementChain(block: Block, ctx: GoEmitContext, indent: number): string[] {
  const lines: string[] = [];
  let current: Block | null = block;
  while (current) {
    lines.push(...emitBlock(current, ctx, indent));
    current = current.getNextBlock();
  }
  return lines;
}

function emitGeneric(block: Block, ctx: GoEmitContext, indent: number): string[] {
  if (isGenericValueBlockType(block.type)) {
    const value = block.getInputTargetBlock("VALUE");
    return value ? emitBlock(value, ctx, indent) : [];
  }
  if (block.type === "xml_element" || block.type.startsWith("schema_")) {
    return emitXmlOrSchema(block, ctx);
  }
  if (block.type === "json_object" || block.type === "json_array") {
    return emitJson(block, ctx, indent);
  }

  const props: string[] = [];
  for (const input of block.inputList) {
    if (!input.name.startsWith("TARGET_") && !input.name.startsWith("SCHEMA_OPT_")) continue;
    const attr = input.name.replace(/^TARGET_|^SCHEMA_OPT_/, "");
    if (input.type === STATEMENT_INPUT_TYPE) {
      const chain = emitStatementList(block.getInputTargetBlock(input.name), ctx, indent);
      if (chain) props.push(`"${attr}": ${chain}`);
      continue;
    }
    const child = block.getInputTargetBlock(input.name);
    if (!child) continue;
    const rendered = emitBlock(child, ctx, indent + 1);
    if (rendered.length) props.push(`"${attr}": ${rendered.join("")}`);
  }
  if (!props.length) return [];
  return [`{${props.join(", ")}}`];
}

function emitStatementList(
  first: Block | null,
  ctx: GoEmitContext,
  indent: number,
): string | null {
  if (!first) return null;
  const parts: string[] = [];
  let current: Block | null = first;
  while (current) {
    const rendered = emitBlock(current, ctx, indent);
    if (rendered.length) parts.push(rendered.join(""));
    current = current.getNextBlock();
  }
  if (!parts.length) return null;
  if (parts.length === 1) return parts[0]!;
  return `[${parts.join(", ")}]`;
}

function emitJson(block: Block, ctx: GoEmitContext, indent: number): string[] {
  if (block.type === "json_array") {
    const count = Number((block as Block & { itemCount_?: number }).itemCount_ ?? 0);
    const items: string[] = [];
    for (let i = 0; i < count; i++) {
      const child = block.getInputTargetBlock(`ADD${i}`);
      if (child) items.push((emitBlock(child, ctx, indent + 1)).join(""));
    }
    return [`[${items.join(", ")}]`];
  }
  const props: string[] = [];
  for (const input of block.inputList) {
    if (!input.name.startsWith("TARGET_")) continue;
    const attr = input.name.slice("TARGET_".length);
    const child = block.getInputTargetBlock(input.name);
    if (!child) continue;
    props.push(`"${attr}": ${emitBlock(child, ctx, indent + 1).join("")}`);
  }
  return [`{${props.join(", ")}}`];
}

function emitRmAsJson(block: Block, ctx: GoEmitContext, indent: number): string[] {
  const props: string[] = [];
  const rmType = rmTypeOf(block);
  const nodeId = String(block.getFieldValue("ARCHETYPE_NODE_ID") ?? "").trim();
  if (nodeId) props.push(`"_type": ${goQuote(rmType)}, "archetype_node_id": ${goQuote(nodeId)}`);
  else props.push(`"_type": ${goQuote(rmType)}`);

  if (block.type === "element") {
    const value = block.getInputTargetBlock("VALUE");
    if (value && !value.isShadow()) {
      props.push(`"value": ${emitBlock(value, ctx, indent + 1).join("")}`);
    }
  }

  for (const input of block.inputList) {
    if (!input.name.startsWith(RM_ATTR_INPUT_PREFIX)) continue;
    const attr = input.name.slice(RM_ATTR_INPUT_PREFIX.length);
    if (input.type === STATEMENT_INPUT_TYPE) {
      const list = emitStatementList(block.getInputTargetBlock(input.name), ctx, indent);
      if (list) props.push(`"${attr}": ${list}`);
      continue;
    }
    const child = block.getInputTargetBlock(input.name);
    if (!child || child.isShadow()) continue;
    props.push(`"${attr}": ${emitBlock(child, ctx, indent + 1).join("")}`);
  }

  if (block.type === "party_proxy") {
    const kind = block.getInputTargetBlock(RM_SPECIALIZATION_INPUT);
    if (kind) return emitRmAsJson(kind, ctx, indent);
  }

  return [`{${props.join(", ")}}`];
}

function emitDvAsJson(block: Block, ctx: GoEmitContext, indent: number): string[] {
  const rmType = String(block.getFieldValue("RM_TYPE") || block.type.replace(/-/g, "_")).toUpperCase();
  const props: string[] = [`"_type": ${goQuote(rmType)}`];
  for (const attr of attributesFor(rmType)) {
    if (!isPrimitiveRmType(attr.typeName) && attr.typeName !== "CODE_PHRASE") continue;
    const inputName = block.getInput(`FLD_${attr.name}`)
      ? `FLD_${attr.name}`
      : block.getInput(`OPTFLD_${attr.name}`)
      ? `OPTFLD_${attr.name}`
      : null;
    if (!inputName) continue;
    const child = block.getInputTargetBlock(inputName);
    if (!child || child.isShadow()) continue;
    props.push(`"${attr.name}": ${emitBlock(child, ctx, indent + 1).join("")}`);
  }
  return [`{${props.join(", ")}}`];
}

function emitXmlOrSchema(block: Block, ctx: GoEmitContext): string[] {
  const tag = xmlTagName(block);
  const xmlAttributes = new Set<string>();
  const extra = (block as Block & { extraState_?: { xmlAttributes?: string[]; fields?: Array<{ name: string; xmlKind?: string }> } }).extraState_;
  for (const name of extra?.xmlAttributes ?? []) xmlAttributes.add(name);
  for (const field of extra?.fields ?? []) {
    if (field.xmlKind === "attribute") xmlAttributes.add(field.name);
  }

  const attrParts: string[] = [];
  const inner: string[] = [];

  if (block.type === "xml_element") {
    const textBlock = block.getInputTargetBlock(targetChildInputName("text"));
    if (textBlock) {
      inner.push(...(emitExpressionBlock(textBlock, ctx) ?? emitBlock(textBlock, ctx, 0)));
    }
    let attr = block.getInputTargetBlock(targetChildInputName("attributes"));
    while (attr) {
      if (attr.type === "xml_attribute") {
        const name = String(attr.getFieldValue("NAME") ?? "").trim();
        if (name) {
          const val = attr.getInputTargetBlock("VALUE");
          const rendered = val ? (emitExpressionBlock(val, ctx) ?? emitBlock(val, ctx, 0)).join("") : "";
          attrParts.push(` ${name}="${rendered}"`);
        }
      }
      attr = attr.getNextBlock();
    }
    let child = block.getInputTargetBlock(targetChildInputName("children"));
    while (child) {
      inner.push(...emitBlock(child, ctx, 0));
      child = child.getNextBlock();
    }
  } else {
    for (const input of block.inputList) {
      if (!input.name.startsWith("TARGET_") && !input.name.startsWith("SCHEMA_OPT_")) continue;
      const fieldName = input.name.replace(/^TARGET_|^SCHEMA_OPT_/, "");
      const child = block.getInputTargetBlock(input.name);
      if (!child) continue;
      if (xmlAttributes.has(fieldName) || child.type === "xml_attribute") {
        const rendered = (emitExpressionBlock(child, ctx) ?? emitBlock(child, ctx, 0)).join("");
        attrParts.push(` ${fieldName}="${rendered}"`);
        continue;
      }
      if (isStructureBlock(child.type)) {
        inner.push(...emitBlock(child, ctx, 0));
        continue;
      }
      const rendered = (emitExpressionBlock(child, ctx) ?? emitBlock(child, ctx, 0)).join("");
      inner.push(`<${xmlName(fieldName)}>${rendered}</${xmlName(fieldName)}>`);
    }
  }

  const attrs = attrParts.join("");
  if (inner.length) return [`<${tag}${attrs}>`, ...inner, `</${tag}>`];
  return [`<${tag}${attrs}></${tag}>`];
}

function emitXmlDocument(block: Block, ctx: GoEmitContext): string[] {
  const decl = xmlDeclarationOf(block);
  const standalone = decl.standalone ? ` standalone="${decl.standalone}"` : "";
  const lines = [`<?xml version="${decl.version}" encoding="${decl.encoding}"${standalone}?>`];
  const root = block.getInputTargetBlock(targetChildInputName("root"));
  if (!root) return lines;
  const body = emitBlock(root, ctx, 0);
  const nsAttrs = xmlNamespacesOf(block).map((ns) => ` xmlns:${ns.prefix}="${ns.uri}"`).join("");
  if (nsAttrs && body[0]?.startsWith("<") && !body[0].startsWith("<?")) {
    body[0] = body[0].replace(/^(<\w+)/, `$1${nsAttrs}`);
  }
  lines.push(...body);
  return lines;
}

function isStructureBlock(type: string): boolean {
  return type === "xml_element" || type === "xml_document" || type.startsWith("schema_") ||
    type === "controls_if" || type === "for_each_source" || type === "for_each_list";
}

function xmlTagName(block: Block): string {
  const slot = String(block.getFieldValue("SLOT_ID") ?? "");
  const path = slot.includes(":") ? slot.slice(slot.indexOf(":") + 1) : slot;
  const fromPath = path.split("/").filter((part) => part && !part.startsWith("@")).pop();
  if (fromPath) return fromPath;
  return String(block.getFieldValue("NAME") ?? "element").trim() || "element";
}

function xmlName(value: string): string {
  const safe = value.replace(/[^A-Za-z0-9_.-]/g, "_");
  return /^[A-Za-z_]/.test(safe) ? safe : `_${safe}`;
}

function rmTypeOf(block: Block): string {
  if (block.type === "element") return "ELEMENT";
  const fromType = block.type.replace(/-/g, "_").toUpperCase();
  const field = String(block.getFieldValue("RM_TYPE") ?? "").trim();
  return field ? field.toUpperCase() : fromType;
}
